- .github/workflows/build.yml
Fixes #6 
- Detecting repository using `github.repository`
- Skip running SonarQube task since the `SONAR_TOKEN` secret is not available on forked repositories (which is a good thing)
> Fixed CI pipeline on forked repositories

- .github/workflows/build.yml
- Checking for the existence of `SONAR_TOKEN` now instead of weird if expressions
- Checking if it is either a `push` or a `pull_request` coming from another repo
- There seems to be an issue (https://github.community/t5/GitHub-Actions/Workflow-is-failing-if-no-job-can-be-ran-due-to-condition/td-p/38085) that prevents us from just skipping all jobs in case it is an internal PR so we need to add a fake job ('noop`) so that at least something runs in this case
> Slightly smarter way to handle CI

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/InitializerHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ParameterDeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/StatementAnalyzer.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/ConstructorDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/Expression.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/FunctionDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/NewExpression.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/Type.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/ValueDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/VariableDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/ImportResolver.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
This fixes #22.
It is discussable whether we should update the type of the `ConstructExpression`, if `ConstructorDeclaration` is resolved by the `CallResolver` since it might then have a better type in the hierarchy - or is this automagically done now anyway?
> Implemented type listening in ConstructExpression

- src/main/java/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/EOGTest.java
- src/test/resources/cfg/ShortCircuit.java
Fixed a mistake in the EOG where the short-circuit evaluation of && and || was not considered.
Fixes #31
> Adds a bugfix for #31 and adds some comments at other places

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- src/test/resources/functiondecl.cpp
There was a bug in the way we add "dummy" return statements. If the function contained only 1 line and this line was already a return statement, a second return statement was added.
Additionally, I have introduced a new property on nodes called `implicit`, this should be used instead of the now deprecated `dummy` property to denote that this node is valid here, but was added to the CPG because it was only implicitly here, i.e. the aforementioned return statements. This will probably also apply to implicit casts or the implicit use of the `this` statement.
We need to think about how we annotate notes that we added as an educated guess, i.e. a reference to a record declaration where we have not seen the actual declaration but know of its existence. Not sure if `dummy` is the correct term
> Fixed an issue that added too many dummy returns

- README.md
- src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java
- src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/helpers/Util.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontendTest.java
CPG was only scanning the files that were explicitly added to its configuration. This PR makes it accept folder or file names. In case of folders, all source files in folder and sub-folders will be parsed.
This PR is required for `feature/cli` branch of analysisserver.
> Allow scanning of all files in a folder

- build.gradle.kts
- src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java
- src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.java
- src/main/java/de/fraunhofer/aisec/cpg/TranslationResult.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/EOGTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/JavaVsCppTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/StaticImportsTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/VariableResolverTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontendTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXCfgTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/DemoTests.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaCfgTest.java
It seems that the ICU dependency was removed by accident, but it is needed to handle eclipse CDT problem descriptions.
> Restored ICU dependency and made sourceLocations consistent

- src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontendFactory.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.java
- src/test/java/de/fraunhofer/aisec/cpg/ScopeManagerTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/SubgraphWalkerTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/BotanExampleTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLiteralTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXSymbolConfigurationTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java
Inside the Tests when creating the Frontend.
> ScopeManager is now created only once per analysis and for each unit test, not implicitly for every language frontend.

- .github/workflows/build.yml
It seems that this GitHub bug is fixed and this noop CI job is no longer needed
> Removed obsolete noop CI job

- src/main/java/de/fraunhofer/aisec/cpg/helpers/Util.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/BranchSemanticEOGPass.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/BSEOGTest.java
When node fields are of a sub-type of `Collection`, it is required that it is a mutable type. Immutable types do not have the default constructor (the one without arguments). The default constructor is however required by `OverflowDatabase.vertexToNode()` for the instantiation of a collection of the respective type (cf. `.getDeclaredConstructor().newInstance()`).
Methods such as `Set.of(..)` or `.collect(Collectors.toSet())` return immutable collections and cannot be used.
This PR turns all immutable collections into mutable ones.
> Fix: vertexToNode requires mutable fields, otherwise throws NoSuchMethodException

- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
In [1] and [2], `ExpressionHandler` simplifies the AST by replacing some nodes by a `FieldAccessExpr`. However, the newly created `FieldAccessExpr` lacks some properties - especially its `parent`, `range`, and `tokenRange` are null. This results later in an `IllegalArgumentException` when a rule violation is found at that node and we try to retrieve its position in the code.
This PR fixes #96. But the original author might want to review and possibly simplify the method in general.
[1] https://github.com/Fraunhofer-AISEC/cpg/blob/487558afba9539db62484b02eb23112ecc85478a/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java#L498
> Fix for null parent of field expression, leading to missing locations.

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/RecordDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/ImportResolver.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/Pass.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/TypeHierarchyResolver.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/TestUtils.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/JavaVsCppTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/SuperCallTest.java
- src/test/resources/superCalls/Interface1.java
- src/test/resources/superCalls/Interface2.java
- src/test/resources/superCalls/SubClass.java
- src/test/resources/superCalls/SuperClass.java
Closes #99 and finishes a task in #37 (SuperExpr support)
> Add support for Java super invocations

- src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java
- src/test/java/de/fraunhofer/aisec/cpg/BaseTest.java
- src/test/java/de/fraunhofer/aisec/cpg/ScopeManagerTest.java
- src/test/java/de/fraunhofer/aisec/cpg/TypeTests.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/ConstructorsTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/EOGTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/FunctionPointerTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/JavaVsCppTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/StaticImportsTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/SubgraphWalkerTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/SuperCallTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/TypedefTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/VariableResolverTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontendTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/BotanExampleTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXBindingsTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXCfgTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLiteralTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXSymbolConfigurationTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/DemoTests.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaCfgTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java
The fix to the type parser turned out to not be robust enough, in cases automatic cleanup after the analysis phase has to be skipped. Thus I fixed it in a better way now, and introduced measures to reset all statically held state before each and every unit test, to avoid undefined results in the future
> Typeparser hotfix

- src/main/java/de/fraunhofer/aisec/cpg/graph/type/FunctionPointerType.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/type/PointerType.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/type/ReferenceType.java
Should close #137 in conjunction with Fraunhofer-AISEC/codyze#22
> Add private default constructors to types for OGM compatibility

- src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java
- src/test/resources/compiling/MemberCallExpression.java
MemberCallExpressions with MemberExpressions as arguments could result in infinite recursion when the `base` of a MemberExpression refers to the 'RecordDeclaration` that contains the original MemberCallExpression.
Resolution of arguments is now limited to `ValueDeclarations`.
With the new type system, I suggest using a `Type` object rather than the `RecordDeclaration` as the value for a `base`.
> Fix: MemberCalls with MemberExpressions

- src/main/java/de/fraunhofer/aisec/cpg/graph/TranslationUnitDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLiteralTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXSymbolConfigurationTest.java
This PR fixes three issues:
1) `TranslationUnitDeclaration.getDeclarationByName()` was pretty useless, as it non-deterministically returned a single element from a set in form of an Optional. Now returns a non-null, possibly empty `Set` has has been renamed to `getDeclarationsByName()`(plural)
2) Bug in `TranslationUnitDeclaration.add(Declaration)` was not never adding `NamespaceDeclaration`s and did not always add to `declarations` list.
3) Adding items to `declarations` list was a bit chaotic: Sometimes using `add()` method, sometimes adding via getter. Has been unified to `add()` now, getters return `UnmodifiableList`.
> TranslationUnitDeclaration

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/CallExpression.java
Codyze relies on the fact that type names in the "fqn" field of `CallExpression`/`MemberCallExpression` do not have any pointer modifiers.
The new type system introduced such modifiers and was simply copying them into the `fqn` field. This PR leaves `Type.getTypeName()` untouched but restores the original representation in `MemberCallExpression.fqn`.
> Fix: Field "fqn" of CallExpression/MemberCallExpression must not contain modifiers "*" or "[]" for PointerTypes

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationListHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/ConstructorDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java
- src/main/java/de/fraunhofer/aisec/cpg/helpers/Util.java
- src/test/java/de/fraunhofer/aisec/cpg/TypeTests.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- src/test/resources/functiondecl.cpp
- src/test/resources/recordstmt.cpp
- src/test/resources/types/fptr_type.cpp
This sets the type of a CPP simple declaration according to its declspecifier instead of the raw signature.
This partially fixes #153. It will not occur that often now probably but the core issue is still there.
> Correctly setting the type of a CPP simple declaration

- src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java
- src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/TypeResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/TestUtils.java
There is one major problem and a few minor ones with the TypeManager:
The major problem is that the singleton instance of TypeManager keeps lists of Types. These Types may refer to RecordDeclarations (including the whole AST of a source file) and were never removed from memory. This is not only a memory leak but also messes up later analysis runs.
The minor problems are related to unclear nullability of fields and the fact that unit tests call TranslationManager.analyze(), but expect that TypeManager is still populated afterwards (although it should in fact be cleaned up). Actually, tests are making false assumptions here.
> Fix leaking types

- src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationListHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/Annotation.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/ConstructorDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/FieldDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/MethodDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- src/test/resources/attributes.cpp
This PR parses C++ attributes (https://en.cppreference.com/w/cpp/language/attributes) as annotation nodes. It is not yet a full annotation support, this will be a separate PR.
> Support for C++ attributes as annotations

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/Expression.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
These are just two small performance quick wins.
Logging each element of the AST is super expensive, especially as a simple line such as 
```
log.debug("Node: {}", node);
```
is actually doing pretty much: It checks for log level, calls `toString()` of a node, which in turn applies some expensive `PrettyPrinter`, does some additional magic to catch endless recursions and then prints the node to console and to the file. Note that the "node" can be the whole source code file, so you were pretty printing a multitude of the whole AST.
> Performance tweaks

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java
- src/test/java/de/fraunhofer/aisec/cpg/TypeTests.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- src/test/resources/functiondecl.cpp
- src/test/resources/types/fptr_type.cpp
Fixes #208 
How should we deal with error cases? For example, specifying `void` more than once is not allowed and also specifying `void` in a named parameter is not allowed. CDT does not enforce this as it just produces a parse tree.
For now, I just emitted a warning but continued parsing the erroneous cases.
> Handling void function parameters

- src/main/java/de/fraunhofer/aisec/cpg/graph/DeclaredReferenceExpression.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/DFGTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/VariableResolverTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/variable_resolution/VRUtil.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXBindingsTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java
Closes #217 
The proposed change *should* actually not have a change in the graph structure, because the relationship of the field stays the same, even though the Java representation has changed.
The `refersTo` field of a `DeclaredReferenceExpression` is no longer a collection, but rather a single reference to a `ValueDeclaration`.
> Converting refersTo back to a single edge field for convenience

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.java
- src/test/java/de/fraunhofer/aisec/cpg/ScopeManagerTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
Fixes #225. Restoring the old behaviour of `ScopeManager::replaceNode`, which was changed in #198 
Also added a test that checks for the correct scope assignment of constructors and method declarations.
> Restored behaviour of ScopeManager::replaceNode

- src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/CompoundStatement.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/ConstructorDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/DeclarationHolder.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/FieldDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/FunctionDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/MethodDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/NamespaceDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/RecordDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/Statement.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/TranslationUnitDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/GlobalScope.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/RecordScope.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/StructureDeclarationScope.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ValueDeclarationScope.java
Declarations in the translation units where the only ones not added by the scope manager. This PR fixes that, leaving the scope manager the singular place to add new declarations. This is necessary to implement things like re-declarables (see #231).
It also contains some cleaner handling of fields, functions, methods and constructors, i.e. checking based on the current scope if it is a function or method. This should remove the need to create function declarations, which are then later on "upgraded" to methods or constructors, effectively removing the need for `ScopeManager::replaceNode` (and #226)
I have added a new interface `DeclarationHolder`, which CPG nodes can implement, which denotes that this node holds further declarations. It basically consists of one method, `addDeclaration`, …
> Adding declarations to translation units through ScopeManager

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java
- src/test/resources/types/fptr_type.cpp
As found by @peckto when trying to parse the eLua library
> Fix issue when parsing functions whose name is in extra parentheses

- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/UninitializedValue.java
- src/main/java/de/fraunhofer/aisec/cpg/helpers/ControlFlowSensitiveDFG.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/DFGTest.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/calls/ConstructorsTest.java
- src/test/resources/dfg/BasicSlice.java
- src/test/resources/dfg/DelayedAssignmentAfterRHS.java
Fixes multiple issues with incorrect DFG edges.
- VariableDeclaration should not contain any outgoing DFG edges.
- The replacement of DFG edges in an assignment must be delayed until the assignment has been completely processed, in order to avoid the issue that a rhs DeclaredReferenceExpression has a dfg edge from the las. E.g.: a = a + b.
None
None
> DFG Hotfix

- src/main/java/de/fraunhofer/aisec/cpg/helpers/LocationConverter.java
This is a priority hotfix to fix https://github.com/Fraunhofer-AISEC/codyze/issues/95.
Please release a 3.0.1 version ASAP.
> Hotfix: Do not use URI in LocationConverter

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java
Fixes #252: `ScopeManager::getCurrentRecord()` is declared as `@Nullable`, so one should not assume that it is safe to call `getThis()` on it.
> Fixed NPE in ExpressionHandler

- build.gradle.kts
This adds support for the usage of Kotlin within the project. This is somewhat up for discussion. I would really appreciate
it, some things such as #276 would depend on it (and #231 could be easier implemented in Kotlin) and I am rather keen on the language itself. 
There is pretty much no complication between using Java and Kotlin in the same project, it works quite well. There is however the small drawback of having two languages within the same project, even if they compile to the same platform. We do use similar paradigms in other projects already, though.
> Added support for Kotlin

- src/main/java/de/fraunhofer/aisec/cpg/helpers/LocationConverter.java
- src/main/java/de/fraunhofer/aisec/cpg/sarif/PhysicalLocation.java
- src/test/java/de/fraunhofer/aisec/cpg/helpers/BaseAttributeConverterTest.java
- src/test/java/de/fraunhofer/aisec/cpg/helpers/LocationConverterTest.java
Loading a node from a Neo4j database that contains a PhysicalLocation throws a MappingException that is caused by a ClassCastException.
The call:
session.query(Node::class.java, "MATCH (n) RETURN n", HashMap<String, Any>())
The ClassCastException is caused by the conversion of a Long to a Integer in the LocationConverter and toIntExact expects a long value.
Therefore, I replaced the dangerous conversion with Long.parseLong and tested it.
> Ogm compatibility

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/helpers/LocationConverter.java
- src/main/java/de/fraunhofer/aisec/cpg/sarif/PhysicalLocation.java
For some reason `DeclarationHandler::handleSimpleDeclaration` did not always use `getTypeStringFromDeclarator` leading to some weird types in some fields.
> Fixing some minor issues with fields

- src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/MemberCallExpression.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/MemberExpression.java
This helps to differentiate between -> and . calls and field accesses. It currently is present on `MemberExpression` and `MemberCallExpression` until #298 is decided.
Fixes #297
> Added operatorCode to member expressions and member call expressions

- build.gradle.kts
Reverts Fraunhofer-AISEC/cpg#282
Fixes #304
> Revert "Update dependency com.github.javaparser:javaparser-symbol-solver-core to v3.18.0"

- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
One does not simple catch a `RuntimeException` apparently.
Fixes #308
> Catching nested JavaParser exception in resolve()

- src/main/java/de/fraunhofer/aisec/cpg/helpers/Util.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java
Currently we have the root node as branching node to keep the semantic information of the language-feature that branches while traversing the EOG. To keep EOG and DFG coherent and later build a propper PDG we prolong the dfg paths to the branching node.
I added the DFG edges where I added the EOG-Edges to the root node: in the EOG-pass- A strategy pattern would be nice to make the root node configurable for EOG and DFG but so far I could not find an easy way to integrate one for the EOG pass.
Root node of language feature if is a sink for the EOG of the condition and then branches out. For certain applications this rootnode allows traversals to use the root node like a jumpi 
DFG edge from condition to the language-feature root node that acts as branching condition.
> Prolongs dfg graphs to the root of a language feature 

- build.gradle.kts
- src/main/java/de/fraunhofer/aisec/cpg/ExperimentalGraph.kt
- src/main/java/de/fraunhofer/aisec/cpg/TranslationResult.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/Graph.kt
- src/test/java/de/fraunhofer/aisec/cpg/graph/QueryTest.kt
- src/test/java/de/fraunhofer/aisec/cpg/graph/TranslationResultTest.kt
This is work in progress. This adds a `Graph` class, which offers a simple interface to query its content with openCypher (https://opencypher.org). It is tied to the translation results using a Kotlin extension  `TranslationResult.graph` and can be used like this:
```Kotlin
val graph = result.graph
var nodes = graph.query("MATCH (m:MethodDeclaration) RETURN m")
```
Only a very limited subset of openCypher is supported for now. This includes
- Simple `MATCH` for nodes with a simple `WHERE` query, such as `MATCH (n) WHERE n.name = "myName" RETURN n`
- Very basic relationship queries, such as `MATCH (n:SomeType)-[:SOME_EDGE]->(m:OtherType) RETURN n`, also including simple `WHERE` constrains on the nodes, but not on the edge
- Can now either return the left or ride side variable of a …
> openCypher integration

- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
This is a quick fix for #327.
There are many other `resolve()` calls, that are not really guarded at all. Seems like we need to be one crash at a time.
> Fixed #327 by removing unnecessary resolve() call

- src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/TypedefTest.java
- src/test/resources/typedefs/typedefs.cpp
Fixes #320 
I am still not a big fan of the fact that the type manager does some C++ specific AST handling, but at least this fixes a problem with tab white spaces.
> Handling typedefs with tabs

- .gitignore
- src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java
- src/test/resources/fix-328/Animal.java
- src/test/resources/fix-328/Cat.java
This slightly changes the way types are "resolved" / guessed in Java. Mainly, it updates the type guessing in the following way:
- First, java parser is used to trying to resolve it
- If that fails, the type is check against the imports to find out the FQN
- NEW: If that fails, the current package name (if there is one), is prepended in front of the class name
This helps resolving types within the same package that do not have an import statement.
Fix for #328
> Improve Java FQN type guessing

- src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/edge/PropertyEdge.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/types/ObjectType.java
- src/main/java/de/fraunhofer/aisec/cpg/graph/types/Type.java
- src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/calls/CallResolverTest.java
- src/test/resources/calls/implicitcast/ambiguouscall.cpp
- src/test/resources/calls/implicitcast/implicitcast.cpp
This PR closes #325.
- The CallResolver is now able to resolve CallExpression, where an implicit cast is necessary to match the signature of the corresponding FunctionDeclaration
- An implicit CastExpression node is added when a CallExpression needs to perform a cast to be resolved
> CallResolver Refinement for Calls with Implicit Cast

- src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/MethodDeclaration.java
- src/test/java/de/fraunhofer/aisec/cpg/enhancements/VisitorTest.java
- src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java
Adding the AST annotation to the receiver property of a method declaration to help the type resolver clean up duplicate types.
Fixes #387
> Added AST annotation for receiver property

- src/main/java/de/fraunhofer/aisec/cpg/frontends/python/JepSingleton.kt
Introduces the `CPG_JEP_LIBRARY` environment variable so that we can directly specify an alternative location for the jep installation if it is not installed at a well known path.
> Add Environment Variable to Specify Path to JEP

- cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/TranslatePlugin.kt
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/edge/PropertyEdgeConverterManager.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/UnaryOperator.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
- cpg-library/src/test/java/de/fraunhofer/aisec/cpg/enhancements/calls/CallResolverTest.java
- cpg-library/src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- cpg-library/src/test/resources/calls/ignore-return.cpp
The CPG aims to be a fuzzy parser and not a compiler. We therefore have more leeway when parsing declarations than a compiler. We therefore, explicitly should NOT check, whether a declaration is really before its usage. The simple reason for that is that we want to be able to analyze code fragments, i.e. if the definition was in a header file that we did not see.
A discussion point might be whether, we want to introduce a flag that enables a more "stricter" compiler-like way in the call resolver. But somehow, I am not sure, whether this makes too much sense, given the use cases we mostly serve.
Closes #457
Addresses the WPDS issue in https://github.com/Fraunhofer-AISEC/codyze/pull/184
> Getting rid of `definedBefore` in `CallResolver`

- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/HasInitializer.kt
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/FieldDeclaration.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/VariableDeclaration.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/NewExpression.java
Mainly needed for better in-memory graph traversal in Codyze.
> Added `HasInitializer` interface for fields and variable declarations

- .github/workflows/build.yml
* Only really publish, when tag does not contain `beta`
* Fixed javadoc path
> Fixed CI errors

- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
Closes #502 
In the Local Variable case, the Annotation is Attached to each Variable Declaration, although the originally Annotated AST-Element is the `VariableDeclarationExpr`
> Add Annotation Handling for Variables and Parameters

- cpg-library/src/main/golang/expressions.go
- cpg-library/src/main/golang/frontend/frontend.go
- cpg-library/src/main/golang/frontend/handler.go
- cpg-library/src/main/golang/go.mod
- cpg-library/src/main/golang/go.sum
- cpg-library/src/main/golang/lib/cpg/main.go
- cpg-library/src/main/golang/statements.go
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/StatementHandler.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontend.kt
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/StatementAnalyzer.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/typescript/DeclarationHandler.kt
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/ForStatement.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.java
- cpg-library/src/test/java/de/fraunhofer/aisec/cpg/enhancements/EOGTest.java
- cpg-library/src/test/java/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-library/src/test/resources/golang-modules/awesome.go
- cpg-library/src/test/resources/golang-modules/cmd/awesome/main.go
- cpg-library/src/test/resources/golang-modules/go.mod
- cpg-library/src/test/resources/golang-modules/util/stuff.go
- cpg-library/src/test/resources/golang/for.go
* Added support for parsing `ForStatement` in Go. This is also graph changing, as we needed to change the type of the iteration expression to `Statement`.
* Handling `IncDecStmt` as `UnaryOperator`.
* Preparing Go modules support. This is not active yet, just the prep work
* Proper resolution of calls across packages, based on package names. This could be re-used in other language frontends for scoped resolution, but is currently limited to Go
> Improvements to the Go language frontend

- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/StatementHandler.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/StatementAnalyzer.java
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/typescript/DeclarationHandler.kt
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/typescript/TypeHandler.kt
- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/ForEachStatement.java
- cpg-library/src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- cpg-library/src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java
This PR changes the graph: `ForEachStamtents`'s `variable` field becomes a `Statement` (was a `Declaration`) to allow for languages that do not require new variables in for loops but also allow references.
Example:
```python
iter = 1
for iter in [1,2,3]:
pass
```
> ForEachStatement: `variable` is now a `Statement` instead of a `Declaration`

- cpg-neo4j/src/test/java/de/fraunhofer/aisec/cpg_vis_neo4j/ApplicationTest.kt
Somehow, magically, the `@BeforeAll` annotation stopped working in the `cpg-neo4j` test. This is a hot fix. We should investigate this further.
> Somehow `@BeforeAll` stopped working in Kotlin tests

- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/KeyValueExpression.kt
This should solve a non reported Issue where DFGs were incomplete. However we may have to look at other parts of the experimental typescript frontend and discuss how types are propagated as there is no current implementation for that logic.
> Adding `DFG` edge from `value` to `KeyValueExpression`

- cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/Statement.java
`Statement::equals` was using `equals` for its `locals` field instead of the appropriate property edge equal function. This lead to a stack overflow in some cases
> Fixed potential stack overflow in `Statement::equals`

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
This PR adds some additional null safety checks that are needed because of the way passes currently work. Hopefully, this will also make it a little bit easier to identify why under certain conditions the language frontend of a pass is `null`.
> Added null safety checks for language frontend in passes

- README.md
- cpg-core/src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXAmbiguitiesTest.kt
- cpg-core/src/test/resources/function_ptr_or_type_cast.c
- cpg-core/src/test/resources/method_or_function_call.cpp
In CXX there is an ambiguity with the statement `(A.B)(C)`.
`B` can either be a method or a function pointer.
Example:
```cpp
struct A {
void foo(int i) {
}
};
struct B {
void (*bar)(int);
};
void bar(int i) {
}
int main() {
A a;
a.j = 1;
B b;
b.bar = &bar;
// foo is a method
(a.foo)(1);     // Crash
a.foo(2);       // OK
// bar is a function pointer
(b.bar)(3);     // Crash
(*b.bar)(4);    // MemberExpression is missing
return 0;
}
```
Loading the example code into the cpg will result in a crash for the `(A.B)(C)` statements:
```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTUnaryExpression cannot be cast to class org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTFieldReference …
```
> Add test cases for CXX ambiguities

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/ImportResolver.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/TypeHierarchyResolver.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/TypeResolver.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
This PR modifies many of the private functions in the default passes to open them up for modification through subclassing. Members and member functions of the passes are now `protected` instead of `private`. Some functions were `public` and had no purpose in being, therefore, I made them protected as well.
> Adapting visibility modifiers in passes to allow extendabillity

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/StatementHandler.java
Closes #605.
Corrects the computation of the aforementioned nodes in Java where we flatten the hierarchy between case/default statements and the following statements.
> Corrects region and code  for case, default and compound statement of a switch

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/test/java/de/fraunhofer/aisec/cpg/enhancements/templates/ClassTemplateTest.java
- cpg-core/src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
- cpg-core/src/test/resources/cpp-this-field.cpp
This PR adds the `this` field to `RecordDeclarations` with type struct, as in cpp structs are classes.
Because we currently make no difference between a c struct and a cpp struct/class, this does also apply to c structs.
This is nothing new, as we create an implicit constructor for structs already.
Additionally, test-cases are added.
> Add this field to cpp struct as they are classes

- cpg-neo4j/src/main/java/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
This PR adds an option to the cpg-neo4j application to not purge the database before pushing the nodes.
This can be useful, if you want to load multiple projects into one database.
> Add option to not purge db before pushing nodes to neo4j

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/CompilationDatabase.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt
- cpg-core/src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXCompilationDatabaseTest.kt
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_arguments.json
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_commands.json
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_multi_tus.json
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_simple.json
- cpg-core/src/test/resources/cxxCompilationDatabase/includes_1/config.h
- cpg-core/src/test/resources/cxxCompilationDatabase/includes_1/header_1.h
- cpg-core/src/test/resources/cxxCompilationDatabase/includes_2/config.h
- cpg-core/src/test/resources/cxxCompilationDatabase/includes_2/header_2.h
- cpg-core/src/test/resources/cxxCompilationDatabase/main.c
- cpg-core/src/test/resources/cxxCompilationDatabase/main_simple.c
- cpg-core/src/test/resources/cxxCompilationDatabase/main_tu_1.c
- cpg-core/src/test/resources/cxxCompilationDatabase/main_tu_2.c
- cpg-core/src/test/resources/cxxCompilationDatabase/sys_includes/sys_header.h
- cpg-core/src/testFixtures/java/de/fraunhofer/aisec/cpg/TestUtils.kt
This PR extends the `CompilationDatabase` by the following compiler options:
* `-isystem` (system include path)
* `-D` (define symbols)
Additionally, test-cases for the current feature set of the  `CompilationDatabase` are added.
> Add support for -isystem and -D

- cpg-neo4j/src/main/java/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
This PR adds the option `--topLevel` to the `cpg-neo4j` application, to specify the topLevel directory of the source code to be analyzed. The topLevel attribute of the `TranslationConfiguration` is optional and is mainly/only used by the java language frontend. If no topLevel is given, the java language frontend calculates it based on the largest common path over all source files.
See: 
https://github.com/Fraunhofer-AISEC/cpg/blob/599b44aa57b74a17b7d68356eada2faebaa35e0b/cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt#L494-L497
The second commit does some smaller clean up and refactor.
> Add option `--topLevel` to cpg-neo4j application

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationResult.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/helpers/Benchmark.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/Pass.java
- cpg-core/src/test/java/de/fraunhofer/aisec/cpg/helpers/BenchmarkTest.kt
- cpg-neo4j/src/main/java/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
This PR adds an option to export the benchmark result as json.
I'm not happy with the almost identical functions `getBenchmarkResult` and `printBenchmark`.
The only difference is the format of `Translation config`.
Do you have an idea how to unify this?
Benchmark json example:
```js
{
"Translation config": {
"inferenceConfiguration": {
"guessCastExpressions": false,
"inferRecords": false
},
"frontends": {
"de.fraunhofer.aisec.cpg.frontends.java.JavaLanguageFrontend": [
".java"
],
"de.fraunhofer.aisec.cpg.frontends.cpp.CXXLanguageFrontend": [
".c",
".cpp",
".cc",
".h",
".hpp"
],
"de.fraunhofer.aisec.cpg.frontends.llvm.LLVMIRLanguageFrontend": [
".ll"
]
},
"processAnnotations": false,
"includePaths": [],
"codeInNodes": true,
"failOnError": false,
"disableCleanup": false,
"symbols": {}, …
```
> Add option to export benchmark result as json

- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/DeclarationHandler.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/ExpressionHandler.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguageFrontend.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/StatementHandler.kt
- cpg-language-llvm/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/ExamplesTest.kt
- cpg-language-llvm/src/test/resources/llvm/examples/rust_sample.ll
The parsing of structures was error prone for several reasons: Special characters in the names were parsed by the type parser in C-style and could lead to wrong types. Furthermore, some types were parsed over and over again. This is resolved by caching already known structures.
Closes #733
> LLVM-CPG: Improve parsing of types 

- .github/workflows/build.yml
- cpg-language-go/src/main/golang/go.mod
- cpg-language-go/src/main/golang/go.sum
This PR adds support for parsing Go 1.18 files. The CPG does not yet translate Go generics into template nodes.
> Support for Go 1.18

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/helpers/Util.java
- cpg-core/src/test/java/de/fraunhofer/aisec/cpg/enhancements/TypedefTest.java
- cpg-core/src/test/resources/typedefs/typedefs.cpp
This PR fixes a bug in the handling of the "multiple typedef statement":
```cpp
typedef int myIntA, intIntB;
```
We detect this by splitting at `,`
In c++ and templates, this gets more complicated:
```cpp
typedef T<int, int> B;
```
I fixed this inside the `Util.containsOnOuterLevel` function.
The solution is not optimal and there might be even more corner cases.
But for now this prevents the cpg from crashing.
Additionally, we do not fully support template classes yet.
> Fix detection of multiple typedef statement

- .github/workflows/build.yml
`find` returns success even if the `exec` part does not (as dictated by the standard). This makes the workflow fail if `pycodestyle` fails.
> Fix: check return code of pycodestyle

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/InitializerListExpression.java
- cpg-language-go/src/main/golang/expressions.go
- cpg-language-go/src/main/golang/frontend/handler.go
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-language-go/src/test/resources/golang/dfg.go
- cpg-language-go/src/test/resources/golang/values.go
Currently, the declaration of a variable and the expression that represents an object literal, e.g., `d := &Data{}` were not connected with a DFG edge. This was due to the fact that there is not real object literal expression in the CPG and we need to "emulate" it with a combination of a `ConstructExpression` and a `InitializerListExpression`.
Furthermore, a DFG edge was missing in `InitializerListExpression::addInitializer`, it was only set in `setInitializers`.
> Fixed missing DFG edges in Go frontend

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/ClassTemplateDeclaration.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/TemplateDeclaration.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/edge/PropertyEdge.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/ArrayCreationExpression.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
* Fixed stack overflow in `ClassTemplateDeclaration::equals`
* Fixed stack overflow in `ArrayCreationExpression::equals`
* Fixed stack overflow in `CallExpression::equals`
* Fixed class cast exception in `TypeManager::getCommonType`
* Fixed NPE in `CallResolver::getCallSignature`
> Fixed various crashes in the CPG

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/processing/strategy/Strategy.java
`Strategy::AST_FORWARD` was using its own weird implementation instead of just re-using the `SubgraphWalker::getAstChildren`. This PR fixes that.
> Fixed `Strategy::AST_FORWARD`

- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/PerformanceRegressionTest.kt
It seems the GitHub runners are getting slower and sometimes they do not hit the 15s target. Performance is still good locally, so we increase the timeout to 20s for less flaky tests.
> Increased timeout for regression test to 20s

- jitpack.yml
This finally enables the build of the `go` language frontend on jitpack builds. Note however, due to the nature of the go library, only the native libraries for linux are included in the jar. This is due to the fact that we need to use `cgo` in order to interface with JNI and `cgo` does not allow cross-compiling the library to other platforms.
> Build go language frontend on jitpack

- cpg-core/build.gradle.kts
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/CompilationDatabase.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXCompilationDatabaseTest.kt
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_arch.json
- cpg-core/src/test/resources/cxxCompilationDatabase/main_arm64.c
This PR adds support for the `-arch` clang command in the compilation database by automatically adding an appropriate symbol to the language frontend.
> Added support for `-arch` clang command in compilation database

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/MultiValueEvaluator.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/SizeEvaluator.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluator.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/EvaluateExtensions.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/UnreachableEOGPass.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/Query.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryTree.kt
- cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/OutOfBoundsCheck.kt
The package name for the `ValueEvaluator` was `.graph`, even though it is (correctly) placed in the `.analysis` folder. Maybe this also fixes the issue with 0 % coverage in sonarqube.
> Fixed package of `ValueEvaluator`

- cpg-language-go/src/main/golang/frontend/handler.go
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-language-go/src/test/resources/golang/literal.go
This PR models `nil` as a null literal, similar to all other languages. This should also make it now compatible with the `ValueEvaluator`, etc.
Fixes #447
> Implementing `nil` as a literal in the Go language frontend

- cpg-all/build.gradle.kts
- settings.gradle.kts
Fixes issue when adding the cpg project as an 'includeBuild' in a project that uses project accessors (see: https://github.com/gradle/gradle/issues/16608)
> Rename `cpg` submodule to `cpg-all`

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/FunctionPointerCallResolver.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/Pass.java
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CompressLLVMPass.kt
This PR extracts function pointer handling out of the `CallResolver`. This makes the `CallResolver` independent of DFG edges and makes the way free for #905
> Extracting function pointer resolver out of `CallResolver`

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManagerTest.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/StatementHandler.kt
- cpg-language-python/src/main/python/CPGPython/_expressions.py
- cpg-language-typescript/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/typescript/ExpressionHandler.kt
This PR introduces an additional field `callee` in a call expression. The idea behind this field is to have an `Expression` that is being "called" by the call expression. For most cases, this will be a `DeclaredReferenceExpression` pointing to the function declaration. However, in some languages, other things might be "callable".
Note, that this is currently not yet used in the `CallResolver`, but only introduces the field in preparation of #773
> Introduction of `callee` in `CallExpression`

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/Pass.java
The previously used `isAnnotationPresent` check does not properly work with `repeatable` annotations as they are internally collected in a "container" annotation (which is not checked by `isAnnotationPresent`). However, `getAnnotationsByType` also checks containers and seems to work as the name suggests unlike the previously used function
> don't use broken isAnnotationPresent() check

- build.gradle.kts
- cpg-language-python/build.gradle.kts
This PR fixes a problem that was introduced by dokka, where we ended up with an empty javadoc jar.
> Fixed javadoc jar generation with dokka

- cpg-console/build.gradle.kts
- cpg-core/build.gradle.kts
- cpg-neo4j/build.gradle.kts
Currently, we are using an old version of the logging API, which results in a warning when starting the cpg:
```
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:298)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:422)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:408)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
at …
```
> Update slf4j and log4j

- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/PerformanceRegressionTest.kt
We currently experience an issue on GitHub where sometimes (maybe because some hidden quota is hit), the GitHub runners slow down and we are not able to finish the regression test in time (20s), even though it still takes only about 2s on a good machine (aka my MacBook).
This disables parallel processing and might make it just fast enough for those special moments. Let's see.
> Trying to make the regression test slightly faster

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/Name.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/NameTest.kt
- cpg-language-go/src/main/golang/node.go
This PR introduces a new `Name` class which represents all things that have a name. It will be the future decision point of symbol resolving based on local names and namespaces. In the meantime, we provide a bridge using Kotlin property delegation to not break anything (yet).
> Introduce `Name` class and delegate `name` property of `Node` to a backing field

- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/PerformanceRegressionTest.kt
It seems that GitHub runners are getting slower and slower... This test still executes in 3-4s on my MacBook Pro M1.
> Increased performance timeout to 25s because of slow GitHub runners

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt
This is a fix to the issue #709. 
For the following code, 
```
template <int a>
void foo() {
std::cout << "a: " << a << std::endl;
}
template <int a>
void bar() {
foo<a>();
}
```
while calling the ` foo<a>(); `  the template argument `a` was not getting added to the [templateArguments](https://github.com/Fraunhofer-AISEC/cpg/blob/6113010845c7fe43ca87b59dd9fc1e08ad1a5e50/cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt#L235). To fix this issue, the corresponding argument is checked if it is of type `IASTIdExpression` and then added to the templateArguments.
> Fix issue #709 

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/StatementHandler.java
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.kt
The expression and statement handler in Java were only using the language as a metadata provider. Additionally, some nodes are directly constructing using `new`, which should be avoided anyway.
Fixes #1021
> Using the correct `MetadataProvider` in Java

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/fsm/DFA.kt
While working on Codyze I noticed that the current DFA implementation does not support multiple order evaluations with the same DFA object. This is because the internally used worklist of visited nodes cannot be reset.
This issue did not arise until now because Codyze-v2 created a new DFA object for each order evaluation (see for loop [here](https://github.com/Fraunhofer-AISEC/codyze/blob/v2.3.0/codyze-v2/src/main/java/de/fraunhofer/aisec/codyze/analysis/markevaluation/ExpressionEvaluator.java#L123), which always creates a new [OrderEvaluation](https://github.com/Fraunhofer-AISEC/codyze/blob/6487ef495bc257d1b1a0a3428c78bbda94a49dff/codyze-v2/src/main/java/de/fraunhofer/aisec/codyze/analysis/markevaluation/OrderEvaluator.java#L50) object)
> fix DFA.initializeOrderEvaluation to allow multiple evaluations

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/Name.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/NameTest.kt
- cpg-core/src/test/resources/cxx/recordstmt.cpp
- cpg-language-go/src/main/golang/frontend/handler.go
- cpg-language-go/src/main/golang/language.go
The FQN of method decorations for unknown classes were wrong. Additionally, there was too much boilerplate code in the C++ method name handling (there still probably is). This PR relieves some of this pain.
> Fixed C++ FQN for methods with unknown classes

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/fsm/DFA.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/fsm/DFAOrderEvaluator.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/fsm/ComplexDFAOrderEvaluationTest.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/fsm/DFAEqualityTest.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/fsm/FSMTest.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/fsm/SimpleDFAOrderEvaluationTest.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/EdgeCachePass.kt
This pull request improves the DFA order evaluation in two aspects: 
- it allows a CPG node to correspond to multiple names allowing following syntax in Codyze/Coko:
```Kotlin
order(testObj::constructor) {
+testObj::start.use { call(1) }
+testObj::start
+testObj::finish
}
```
In this case, `testObj::start.use { call(1) }` corresponds to the set of `start` nodes that have `1` as an argument compared to `testObj::start`, which returns all nodes of `start`. The CPG nodes contained in both sets therefore need the ability to map to multiple names.
- Implement the `consideredResetNodes` feature, which allows the `DFAOrderEvaluator` to reset the order evaluation on a base when a reset node is encountered. This allows the correct evaluation of cases like the following:
```Java
Botan p7 = new …
```
> Improve order evaluation

- .github/workflows/build.yml
- README.md
- buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
- gradle/libs.versions.toml
We should take the chance with the next major CPG version to upgrade CDT. The recent version of CDT however needs Java 17, making this a great time to upgrade to this LTS version.
> Upgrade Eclipse CDT to 11 and Java to 17

- buildSrc/src/main/kotlin/cpg.frontend-dependency-conventions.gradle.kts
- cpg-all/build.gradle.kts
- cpg-console/build.gradle.kts
- cpg-neo4j/build.gradle.kts
@maximiliankaul noticed that both the cpg-neo4j and the cpg-console are missing the optional language frontend dependencies. This pull request fixes that by introducing a new convention plugin.
> Add frontend dependency plugin

- .github/workflows/build.yml
- build.gradle.kts
Registers two new compound tasks: 'publishAllModules' and 'publishAllModulesToMavenLocal'.
These tasks depend on the 'publish' respectively 'publishToMavenLocal' tasks in each sub module.
Fixes the github workflow to use the new publishAllModules task
> Fix gradle publishing

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/ValueDeclaration.java
> Fixed unwrap of `usage` in `ValueDeclaration`

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/DeclarationStatement.java
We may want to filter unreachable paths from the results of the `followNextEOG` and `followNextEOGUntilHit` methods. Closes #1049 
I realized that we do not set this property for the `prevEOGEdges` even if it should be a bi-directional property. Unreachable basically means that there's a condition which makes this specific transition `n1 - nextEOG -> n2` impossible. This means that also `n1 <- prevEOG - n2` should be not be relevant for the backwards traversal, right? Should we add this feature as well (@oxisto @konradweiss)?
> Use `UNREACHABLE` property in `followNextEOG` methods

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/CastExpression.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/DeclaredReferenceExpression.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/Type.java
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/ExpressionBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolver.kt
This PR adds several improvements to the C/C++ language frontend. Primarily, we remove reliance to CDT types. This is one more step towards our strategy to use CDT solely as parser, but not do any kind of symbol resolving.
Fixes #28
Fixes #189
> Improvements to the `CXXLanguageFrontend`

- cpg-neo4j/src/main/java/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
The unity build option is an optimization for C/C++ projects, where all source files are loaded as one translation unit, preventing header files from getting parsed twice.
> Add use-unity-build option to cpg-neo4j

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/ResolveInFrontend.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/PopulatedByPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ResolveInFrontend.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/ConstructExpression.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.kt
- cpg-core/src/test/resources/cxx/namespaced_function.cpp
- cpg-language-go/src/main/golang/types.go
Furthermore, this tries to mitigate the problem that types used within such a function could refer to a namespaced entity but are referred with its local name. Since this requires resolving of symbols in a frontend, we introduce a new annotaiton `@ResolveInFrontend` to warn developers.
Fixes #1070
> Correct parsing of functions in namespaces in C++

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/StatementHandler.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/BinaryOperator.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/DFGTest.kt
- cpg-core/src/test/resources/dfg/ReturnTest.java
I forgot to traverse the AST of function declarations to identify all possible return statements in the `DFGPass`. However, there is still an implicit return statement in the function even if it's not necessary. (@konradweiss Can we get rid of it?)
Fixes #1077
> Consider all children to find the `prevDFG` for `FunctionDeclaration`s

- cpg-core/specifications/eog.md
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
Handles key value pairs in the EOG pass. Experimental evaluation in python showed that first the key and then the value seem to be evaluated.
Closes #469
> Add EOG for key value pairs

- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/SizeEvaluatorTest.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluatorTest.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/QueryTest.kt
- cpg-console/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/AnalysisTest.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/DFGTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/EOGTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/calls/ConstructorsTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/calls/SuperCallTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/variable_resolution/VariableResolverJavaTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/FrontendHelperTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/java/StaticImportsTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/types/TypeTests.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/helpers/CommentMatcherTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolverTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/DFGTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/UnresolvedDFGPassTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/VariableResolverTest.kt
This PR makes the `JavaExternalTypeHierarchyResolver` pass mandatory for Java by annotating the `JavaLanguageFrontend` accordingly.
All manual registrations of the pass are removed as they are now obsolete.
> JavaLanguageFrontend always requires JavaExternalTypeHierarchyResolver pass

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/ArrayRangeExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
Adds handling `ArrayRangeExpression`s to the EOG pass and also adds a `step` property to the class. However, I'm not sure if all languages (i.e., c++) use the expressions in a dynamic way. In that case, I'm not even sure how/if this would be modeled in the EOG.
I'd also suggest to rename the class from `ArrayRangeExpression` to `RangeExpression` since we do not really care about the array here (there's not even a way to specify the array).
Closes #377 (and is related to #372).
> Add `ArrayRangeExpressions` to the EOGPass

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/CompilationDatabase.kt
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_arch.json
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_arguments.json
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_commands.json
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_multi_tus.json
- cpg-core/src/test/resources/cxxCompilationDatabase/compile_commands_simple.json
Interpret the include paths in the compilation database as relative to the specified directory (as it is for the source file already).
Ref: https://clang.llvm.org/docs/JSONCompilationDatabase.html
> directory: The working directory of the compilation. All paths specified in the command or file fields must be either absolute or relative to this directory.
main.c
```c
#include "header.h"
int main() {
foo();
return 0;
}
```
compile_commands.json:
```json
[
{
"arguments": [
"/usr/bin/gcc",
"-c",
"-Iinc",
"src/main.c"
],
"directory": "/code/",
"file": "src/main.c"
}
]
```
Folder structure:
```
/code/
├── compile_commands.json
├── inc
│   └── header.h
└── src
└── main.c
```
> Resolve relative include path when loading compilation database

- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/BooleanType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.kt
- cpg-core/src/test/resources/cxx/literals.cpp
- cpg-core/src/test/resources/literals.cpp
This PR improves the parsing of literals in C++. For one, unknown custom suffixes should not result in an error, since we cannot parse them (yet), and not crash the translation. Second, a problem with suffix confusion between float and double has been fixed as well.
This also adds a `BooleanType` as primitive type and correctly sets the C++ boolean type to `bool`.
Fixes #1084
Fixes #1099
> Improved literal parsing in C++

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/CompilationDatabase.kt
When using the unity build mode, all source files are included in a temporary main file.
When using this option together with a compilation database, we need to merge the include paths from all source files in the compilation database and assign them to the temporary main file.
This of course losses the possibility of setting include paths for individual translation units.
> Merge all include paths from compilation database for unity build mode

- gradle/wrapper/gradle-wrapper.properties
Reverts Fraunhofer-AISEC/cpg#1096
This is due to the gradle pipeline failing because Dokka needs an older version of gradle. This update can happen as soon as Dokka 1.8.10  is released.
> Revert "Update dependency gradle to v8"

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguage.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/SubGraph.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/EnumDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/IncludeDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/DesignatedInitializerExpression.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguage.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguage.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
- cpg-language-typescript/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/typescript/JavaScriptLanguage.kt
OGM seems to require `MutableLists` or it will throw a stackoverflow exception (which is very misleading).  I also reviewed the other occurrences of relationships to ensure that we fix this problem everywhere.
In addition, I fixed the inconsistent usage of the `SubGraph` annotation. Annotating properties (or even methods) works but isn't supported by the `SubgraphWalker` (yet).
Closes #1106
> Fix problem with PropertyEdges in EnumDeclaration

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluator.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/Query.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/QueryTest.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/ArgumentHolder.kt
- cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/Type.java
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/ExpressionBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/HasInitializer.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/builder/Fluent.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/VariableDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/IfStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/ReturnStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/AssignExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/BinaryOperator.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/DeclaredReferenceExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/TupleType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/FluentTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/AssignExpressionTest.kt
- cpg-language-go/src/test/resources/log4j2.xml
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
This adds a new statement class, called `AssignExpression` as well as `TupleType`.
The `AssignExpression` holds a list of `lhs` and `rhs` for the respective values on the left and right side. Furthermore, it contains a list of `declarations`, since some languages can declare variables in an assignment-like statement (either implicitly or explicitly). The recommended way to fill these declarations are in an extra pass that runs after all language frontends have been executed.
> Introduce `AssignExpression` to support multiple assignments

- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
Since the `JavaLanguageFrontend` is not part of the `defaultLanguages()` anymore, the `JavaLanguageFrontend` is not loaded for neo4j anymore.
> Optionally enable `JavaLanguage` for neo4j

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/PleaseBeCareful.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolverTest.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguage.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/ApplicationTest.kt
Previously, we put all inferred function declarations in the global scope (the current TU). However, there are cases where the function is actually residing in a namespace declaration and we need to put it there.
This will not (yet) infer the namespace declaration if it is missing. This might even something that is specific to the frontend, e.g., generate namespace declarations out of import statements.
This will also now use the `ScopeManager` in the inference system, allowing for a better integration of inferred nodes. This for example reduces the amount of duplicate inferred nodes, since now just one is created and can be invoked by others.
> Inferring missing functions in namespace declarations

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/FunctionPointerCallResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.kt
- cpg-core/src/test/resources/c/func_ptr_call.c
The function pointer call resolver pass had a hidden blocking dependency on the `ControlFlowSensitiveDFGPass`, in a way that it needed to be executed BEFORE the control flow sensitive DFG was built. This was/is because of inconsistencies between both the "regular" DFG pass and the control-flow sensitive one (which we need to tackle in a seperate PR).
This PR makes resolving function pointers a little bit cleaner, since basically it tries to resolve every `callee` of a `CallExpression` that is of `FunctionPointerType`, regardless of any AST structure or other weird resolving. This also moves the `VariableUsageResovler` a little bit closer to resolving not just variables, but also functions (since in the long term we want to merge it with the `CallResolver`)
> Made the `FunctionPointerCallResolver` compatible with the `ControlFlowSensitiveDFGPass`

- README.md
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/UnknownType.kt
We had to observe some random crashes when using the unknown type map recently with concurrent modification exceptions. This PR should fix this issue.
> Use `ConcurrentHashMap` to keep language-specific `UnknownType`s

- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclaratorHandler.kt
The code property for function declarations must be taken from the parent node.
This is already handled by `applyMetadata`, thus it must not be set when calling `newFunctionDeclaration`.
> Fix code property for function declaration

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/GlobalScope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/DeclaredReferenceExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManagerTest.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/ExpressionHandler.kt
There was a rather delicate bug in the merging functionality of the ScopeManager, that always resulted in a wrong merged global scope.
> Fixed a bug in `ScopeManager::mergeFrom`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/UnresolvedDFGPassTest.kt
Currently, we only infer dfg edges to calls for unresolved functions. This PR also generalizes it to implicit function declarations.
> Infer DFG for calls to implicit functions

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
This PR fixes `collectInitialPasses`. The `PassWithDependencies` were initialized with the `softDependencies` and `hardDependencies` switched (see [constructor](https://github.com/Fraunhofer-AISEC/cpg/blob/main/cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/order/PassWithDependencies.kt#L35) of `PassWithDependencies`).
> Fix `collectInitialPasses`

- buildSrc/src/main/kotlin/cpg.formatting-conventions.gradle.kts
> Removing hidden dependency between `yarnInstall` and `spotlessPython`

- .github/workflows/build.yml
- build.gradle.kts
Try to get rid of shell command and replace it with the given "version" information of the project.
> Get rid of shell command when generating docs

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PrepareSerialization.kt
- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/ApplicationTest.kt
> Convert Neo4j pre-save hooks to cpg pass

- .github/workflows/build.yml
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
- cpg-language-typescript/build.gradle.kts
- cpg-language-typescript/src/main/nodejs/package-lock.json
- cpg-language-typescript/src/main/nodejs/package.json
- gradle/libs.versions.toml
- jitpack.yml
Using nexus-publish plugin instead of maven-publish to publish to Maven Central. Also fixes some issues with jitpack.
> Fix publishing issues

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edge/PropertyEdge.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXCallResolverHelper.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
This PR changes the DFG to use PropertyEdges instead of storing the Nodes directly.
> Change DFG to use PropertyEdges

- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/StatementHandler.kt
- cpg-language-llvm/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguageFrontendTest.kt
Replaces all occurrences of `newBinaryOperator("=")` with `AssignExpression`s in the llvm language module. Fixes #1261
> Use assign expressions in LLVM frontend

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/GotoStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/cxx/fix-1226/header.h
- cpg-language-cxx/src/test/resources/cxx/fix-1226/main1.cpp
- cpg-language-cxx/src/test/resources/cxx/fix-1226/main2.cpp
Some nodes were using an exhaustive list of properties in their `equals` method. However, this also included property, which could loop back to the node itself. For example a function declaration includes all body nodes, which could include a call expression, which included the `invoke` property, which could loop back to the function declaration.
Fixes #1226
> Trying to reduce loops in `equals`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/DeclarationBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TupleDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/ValueDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/VariableDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Expression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/InitializerListExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/HasType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/TupleType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeHierarchyResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TupleDeclarationTest.kt
- cpg-core/src/testFixtures/kotlin/de/fraunhofer/aisec/cpg/TestUtils.kt
- docs/docs/CPG/specs/dfg.md
- docs/docs/CPG/specs/eog.md
This PR adds a new type of `Declaration`, which represenst a tuple of variable declarations. This is primarily needed for languages, such as Go, which support the assignment of multiple values in an initializer. In this case we cannot assign the initializer of the individual variables, but assigned it to the `TupleDeclaration` instead.
Currently, the type of the `TupleDeclaration` and its elements MUST be set to the `AutoType`.
> Added `TupleDeclaration`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/StatementHolder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TranslationUnitDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edge/PropertyEdge.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/FunctionPointerType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/ObjectType.kt
For some reason wrapping of property edges was always assuming that the edges are "outgoing". This of course created major problems if edges were incoming.
> Fixed rather intricate bug in property edge list

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/MultiValueEvaluator.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/NumberExtensions.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/NumberSet.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluator.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/MultiValueEvaluatorTest.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluatorTest.kt
Previously, we just casted most of our numeric types to `Long` when doing arithmetic operations in the `ValueEvalutor`. This PR tries to optimize that by introducing a number of extension functions that under the hood call the necessary Kotlin functions to properly deal with the resulting type based on the bit width.
> More precise types in arithmetic evaluation

- docs/docs/GettingStarted/query.md
> Add more documentation of value evaluation

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TypeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Name.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/TypeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/builder/Fluent.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/RecordDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TypeParamDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/AutoType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/BooleanType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/FloatingPointType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/FunctionPointerType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/FunctionType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/HasType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/IncompleteType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/IntegerType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/NumericType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/ObjectType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/ParameterizedType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/PointerType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/ProblemType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/ReferenceType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/StringType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/TupleType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/Type.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/UnknownType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TemplateCallResolverHelper.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/UnresolvedDFGPassTest.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclarationHandler.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/templates/ClassTemplateTest.kt
Instead of gathering individual type node objects and then squashing them back together, we just make sure that `registerType` only returns the single unique type object. To reduce the number of `Type` nodes needed as input to `registerType`, the `objectType` function does a pre-check now, if a `ObjectType` with the given name already exists, so no new `Type` object is even created at all.
This also removes the "secondary type edge" interface, which was only needed to merge extra usages of types in nodes. Now all type nodes are always referring to the single instance.
> Only store one single unique `Type` nodes for each type

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/LabelStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/EOGWorklist.kt
Currently, the EOG iteration copies the state for each step in the EOG. This consumes quite some resources and it would be great to copy the objects less frequently. One idea is to copy them only when entering/exiting a new basic block and otherwise operate on the same object.
Fixes #1194
> Copy objects less frequently

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/FunctionPointerCallResolver.kt
This PR simplifies and improves the scope handling in the `ScopedWalker`. Previously, the walker tried to enter/leave scopes with a certain heuristic when nodes were iterated or their parent changed. While this worked for most cases, it could diverge from the actual scoping that was established during a frontend run. One such example was when method declarations were declared outside the AST of a class (a common use-case in Go or C++). In this case, the walker left the record scope open after existing the function, since it did not know of its existence (only of the existence of the function scope).
I therefore changed the behaviour in a way that the walker "jumps" directly to the scope of the node, which is recorded in its `scope` variable. I suspect, that at the time of wiriting of the …
> Improved scope handling in `ScopedWalker`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Reference.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolverTest.kt
This PR caches symbol resolutions. This can can significantly speed up the resolution process.
> Caching symbols on symbol resolution

- build.gradle.kts
- gradle.properties.example
- gradle/libs.versions.toml
One might need to copy the example grade.properties manually, since it seems the `sonar.gradle.skipCompile` is a system property, which needs to be set in `gradle.properties`.
> Removed SonarQube warnings

- .github/workflows/build.yml
- build.gradle.kts
- buildSrc/src/main/kotlin/cpg.frontend-dependency-conventions.gradle.kts
- configure_frontends.sh
- cpg-language-ruby/build.gradle.kts
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/DeclarationHandler.kt
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/ExpressionHandler.kt
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/RubyHandler.kt
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/RubyLanguage.kt
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/RubyLanguageFrontend.kt
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/StatementHandler.kt
- cpg-language-ruby/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/RubyLanguageFrontendTest.kt
- cpg-language-ruby/src/test/resources/ruby/function.rb
- cpg-language-ruby/src/test/resources/ruby/iter.rb
- cpg-language-ruby/src/test/resources/ruby/variables.rb
- gradle.properties.example
- settings.gradle.kts
Very primitive implementation of Ruby, moved from http://github.com/clouditor/cloud-property-graph. Primarily used in our research. Not ready for production and only marginally tested.
> Initial implementation of a ruby language frontend

- cpg-neo4j/README.md
- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/ApplicationTest.kt
This PR adds the functionality to export the cpg as json.
The serialization is done via the Neo4j OGM.
Basically the same as when importing to Neo4j Database, just without Database.
So the json export will suffer from known problems, like recursion and bigInt.
Json format might be useful for machine learning or other data science projects.
Proposed json format:
```json
{
"nodes": [],
"edges": []
}
```
Example json file: 
[cpg.txt](https://github.com/Fraunhofer-AISEC/cpg/files/11757931/cpg.txt)
> Export cpg as json via Neo4j OGM

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/builder/Fluent.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Reference.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/Pass.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPassTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolverTest.kt
This calculates a simple cylic complexity for functions and adds a configuration option to specify a max for the control-flow sensitive DFG pass.
> Make control-flow sensitive DFG pass configurable by complexity

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/builder/Fluent.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Reference.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/Pass.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPassTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolverTest.kt
This was causing MAJOR performance problems, since we are using the `hashCode` in the symbol resolver for caching. This had the effect that on deeply nested scopes, performance dropped quite largely.
> Removed `parent` from `hashCode` of `Scope`

- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/ExpressionHandler.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/cxx/parenthesis.cpp
There were more ambiguities when guesssing cast expressions, so I added them.
Fixes #1347
> Improved `guessCastExpressions` in C++ frontend

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclarationHandler.kt
This allows us to overload this specifically for specific languages.
> Moving `hasSignature` to language

- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclarationHandler.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclaratorHandler.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/ExpressionHandler.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/InitializerHandler.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/ParameterDeclarationHandler.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/StatementHandler.kt
Previously, in the CXX frontend, we were supplying the `rawSignature` as code(override) to almost all functions that created nodes. The issue with that is, that this does not respect the `codeInNodes` config option, which might be turned on to save memory.
This PR consequently uses the `rawNode` parameter, which forwards setting code and location to the language frontend, which DOES respect the `codeInNodes` option.
> Avoid using `rawSignature` directly when creating nodes

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/HasAliases.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/ValueDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/VariableDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Reference.kt
Adds the following fields:
* `isGlobal` (getter) to determine if a variable is a local or a global variable. This can make a difference ;)
* `aliases` a list collecting aliases of a reference or a variable (more precisely `ValueDeclaration`)
> Add fields to `Reference`s and `VariableDeclaration`s

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/Declaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TemplateDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/ValueDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/Statement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Expression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/Type.kt
- cpg-language-typescript/src/main/nodejs/package.json
Solves #1373 
By adding the @NodeEntity to abstract classes of nodes, neo4j again persists labels like `Type`, `Expression`, `Declaration`. This is only necessary for abstract classes as super classes that are not abstract get the label persisted.
> Add NodeEntity to abstract node classes to get them persisted to neo4j

- README.md
- buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
- cpg-console/build.gradle.kts
- cpg-core/build.gradle.kts
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/helpers/LocationConverterTest.kt
- cpg-language-cxx/build.gradle.kts
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/RubyLanguageFrontend.kt
- gradle/libs.versions.toml
This PR cleans some weird dependencies that were misused in the language frontends and also updates CDT to 11.3.1. This means, that the ivy repository needs to be updated for all users. The README.md was adjusted accordingly.
> Cleanup of depdendencies and CDT update

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlDependenceGraphPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ProgramDependenceGraphPass.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/ProgramDependenceGraphPassTest.kt
This PR:
- Tries to remove some confusing edges from PDG
- Fixed an endless loop in PDG
It is cherry-picked and cleaned up from #1382
> Fixes to PDG/CDG

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Handler.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/StatementHandler.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/StatementHandler.kt
- cpg-language-typescript/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/typescript/StatementHandler.kt
This PR adds a clarifying comment to the node builder, why set set the location and code there. It also removes the latest remnants of setting the location in the handlerClarifying setting location and code in the Node builders
> Clarifying setting location and code in the Node builders

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-language-go/src/test/resources/golang/cast.go
In some frontends (e.g., the Go frontend) we are replacing certain nodes in an extra pass, while iterating with the `ScopedWalker`. One such usecase is to replace calls with casts. Previously, when doing so, chained replacement of calls were a problem, since the original replaced value was stil registered in the walker and was used to determine further AST children to "walk" on, instead of the new node.
This adds a function to register such replacements with the walker.
> Added `registerReplacement` to `ScopedWalker`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/StatementHandler.kt
This PR allows the setting of a node's code and location region as the code and location of its children.
Sometimes, when we translate a parent node in the language-specific  AST with its children into the CPG AST, we have to set a specific intermediate Node between that has no language-specific AST that can give it a proper code and location.
This PR provides the function `codeAndLocationFromChildren(frontend: LanguageFrontend<S, *>, parentNode: S)` that is purely optional and can be used in language frontends to cover the use-case mentioned above and set the region of the node to the start and end region of its children. The code is then extracted from the language-specific AST parent using the newly determined location region.
The function modifies the base node, meaning it should be …
> Code and location from children

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/RegionUtils.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXHandler.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/StatementHandler.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/DeclarationHandler.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoHandler.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/SpecificationHandler.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/StatementHandler.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/StatementHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonHandler.kt
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/RubyHandler.kt
Instead of directly setting the code and location provider in the implementation of the `CodeAndLocationProvider` we rather now have an implementor of this interface implement the methods `codeOf` and `locationOf` and set the code/location in the node builder. This is more in line with the other providers, since they should *provide* a value, but not *set* it.
> Better design of the `CodeAndLocationProvider`

- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
Initially, the `--custom-pass-list` option was combined with the `--no-default-passes` option.
Re-thinking about it, this seems an unnecessary limitation.
When using the custom pass list option together with the default passes, passes, which are not in the default list, can be added easily (e.g. `ProgramDependenceGraphPass`).
> Make custom pass list option independent of default passes

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationResult.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Component.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXCompilationDatabaseTest.kt
Adding TUs to a component has not been synchronized. This is obviously a bad idea when parsing multiple files in parallel. It seems to cause at least some of the randomly occurring test failures.
> Synchronize adding TUs

- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/testcases/Query.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/InferenceConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/Util.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/UnresolvedDFGPassTest.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CLanguage.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CPPLanguage.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/ExpressionHandler.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXInferenceTest.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolverTest.kt
- cpg-language-cxx/src/test/resources/cxx/inference.cpp
- cpg-language-cxx/src/test/resources/cxx/inference.h
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolverTest.kt
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/ApplicationTest.kt
This PR does some cleanup and improvements to the inference systems. It is made more configurable, with more options added to `InferenceConfiguration`.
For example, currently, the `Inference` class only infers fields. However, some languages (such as C/C++) have global variables, which we can also infer.
Note, that we intentionally *NOT* infer local variables, since we assume that we have incomplete code, that is probably complete within a function, but not complete in the sense that translation unit files or headers are missing.
This also aligns the DFG of inferred functions more to non-inferred ones and adds inferred methods to the AST.
> Several improvements and cleanups to the `Inference` system

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
Getting the token code for comments from the library itself and use constant as index for the token type.
> Cleaning up comment parsing and matching

- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.kt
The culprit was a hard `as` cast, which should have been a smart `as?` cast.
Fixes #1377
> Fixed class cast exception in `createImplicitThis`

- cpg-language-typescript/build.gradle.kts
Recent updates to rollup, etc. need at least Node.js version 20.
> Using Node 20

- buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
- cpg-console/build.gradle.kts
- cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/CpgConsole.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- gradle/libs.versions.toml
Instead of reyling on maven central, we are using a JitPack release for the console. This is ok, since the console is a standalone binary and is not to be used as a dependency.
Fixes #1426
Fixes #1439
Fixes #1272
> Using ki-shell from JitPack

- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Schema.kt
Fixes an Issue were inherited relationsships were not added to the node and adds a property telling if they are inherited.
Fixes an Issue causing the Node not having `Node` in its labels.
Adds the property `abstract` to the schema of a node signalling whether or not it can be seen in a graph.
> Several small fixes to the Schema to JSON printing

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.kt
- cpg-language-java/src/test/resources/compiling/enums/Enums.java
- cpg-language-java/src/test/resources/compiling/enums/EnumsImport.java
Concerning #1445:
- `EnumDeclaration`s now get assigned their class members, just like `RecordDeclaration`s.
- The `ImportResolver` correctly identifies entries and other members of `EnumDeclaration`s that are imported.
- combined the processing of static and non-static `ImportDeclaration`s, separating them afterwards by `isStatic` (a comment indicated that something similar was done earlier and then undone)
- in some cases re-merged the processing of `EnumDeclaration`s and `RecordDeclaration`s and refactored out common parts into separate methods
- added a test and test files for the above changes
> Add members, methods and imports to EnumDeclarations

- jitpack.yml
It seems that the version of Node we are using cannot be used in this old build environment of JitPack.
> Disabling TypeScript builds on JitPack

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EdgeCachePass.kt
The `EdgeCachePass` acts as a cache for AST, DFG and EOG edges.
Currently, the `EdgeCachePass` does not depend on any other passes. This can cause incomplete edge caches, if passes, excecuted later, add new edges.
This change adds pass dependencies for all current passes that add AST, DFG or EOG edges.
> Adds pass dependencies for `EdgeCachePass`

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/Query.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/QueryTest.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/ShortcutsTest.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CDataflowTest.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/ExpressionTest.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
We had a problem that the extension functions, such as `followNextDFGEdgesUntilHit` were following all DFG flows, including partial ones. This lead to unexpected results.
> Only follow full DFG flow in `followNextDFGEdgesUntilHit` and similar

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-language-go/src/test/resources/golang/inference.go
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/ApplicationTest.kt
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Neo4JTest.kt
- cpg-neo4j/src/test/resources/log4j2.xml
This PR changes the type that is forwarded to the inference type. Previously any type (including a pointer type) was forwarded to `inferRecordDeclaration`. This was not working for pointer types. Now instead, the `root` type is used, which points to the element type in case of (chained) pointer types. Also changed an error message in the scope manager to a warning and improved logging in the inference system slightly.
This also makes the behaviour of the `SymbolResolver` deterministic again, this was caused by a unfortunate combination of `toSet` calls.
Fixes #1475
> Fixing record inference and making `SymbolResolver` deterministic again

- docs/docs/CPG/specs/dfg-function-summaries.md
- docs/docs/CPG/specs/dfg.md
- docs/docs/CPG/specs/eog.md
> Docs fixes

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeHierarchyResolver.kt
Due to a bug in the symbol resolver, we did not resolve fields that are in base classes of classes correctly.
> Fixes incorrect field resolution in base classes

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageTest.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CLanguage.kt
- cpg-language-cxx/src/test/resources/variables_extended/cpp/scope_variables.cpp
This PR adds the way `Type.isDerivedFrom` works. More concretly, we are once again taking the "wrap state" of the type into account. This means that pointer types and non-pointer types will not match even though their root types derive from each other. This was the way this function behaved in the past and it seems this was changed at some point. 
This behaviour seems to be less-error prone because it led to some weird over-approximations in call resolving, basically ignoring wether a type was a pointer or not. To replicate the behaviour previous to the PR, you can use `type.root.isDerivedFrom(other.root)`, if you really want to just match the root types.
> Improved stability of `isDerivedFrom` decisions

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/Pass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ReplaceCallCastPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/order/RequiresLanguageTrait.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CPPLanguage.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXExtraPass.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguage.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
Multiple languages, such as Go and C++ support "functional style casts", in the form of `int(5)`. During the frontend parsing, they are indistinguishable from function calls. Therefore, we need to do a cleanup after all types are known but before other passes are invoked that replace those calls with casts. The proposed solution is to include a new language trait `HasFuntionalCasts` and to move the logic from the `GoExtraPass` into a separate, language-neutral one.
Fixes #1487
> Extracted call/cast replacement into separate pass

- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclarationHandler.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXExtraPass.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/c/issue-194/bar.c
- cpg-language-cxx/src/test/resources/c/issue-194/foo.c
- cpg-language-cxx/src/test/resources/c/issue-194/foo.h
This PR finally connects all declarations in C/C++ to their respective definitions in an extra pass, more specifically the already existing `CXXExtraPass`. Since C/C++ is the only language where this is (currently) relevant, I would propose sticking to this "language-specific" solution.
Fixes #194
> Extracting connecting declarations and definitions in C++ to extra pass

- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.kt
When javaparser tries to resolve the type of `this` it failed in a case where it was used in an anomymouse inner class. In this case we now take the name of the current record from the scope manager.
> Fixing javaparser resultion error

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
Clarifies some details I was wondering about while looking into the method.
> Extension to the documentation for extractScope

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/order/PassWithDependencies.kt
Fixes #1480 
- Things are printed twice (once empty) because a default `config` of the `TranslationManager` is built (which is empty) and one actual config set by `TranslationManager.Builder.config()`. Fix: No default config if it is not required.
> Fix output of pass ordering and dependencies

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluator.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluatorTest.kt
Previously, the `ValueEvaluator` was assuming that a conditional expression was only using the `==` operator.
Fixes #1527
> Take operator into account when evaluating conditional expressions

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/ValueDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Expression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/ApplicationTest.kt
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Neo4JTest.kt
We need to adjust the `UnknownType` once we know the language, otherwise there is a problem when comparing types. This stems from the fact that we initialise the type property with an unknown type that has a `null` language.
> Adjusting `HasType` type once a language changes

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DynamicInvokeResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/configuration/PassWithDependencies.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/configuration/PassWithDepsContainer.kt
> Adding soft from DynamicInvokeResolver to ControlFlowSensitiveDFGPass

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/ExpressionHandler.kt
> Implement ast.Subscript and ast.Slice

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/InferenceConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TypeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ReplaceCallCastPass.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/ExpressionHandler.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXExtraPass.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/cxx/parenthesis.cpp
Follow up to #1406. This PR now resolves cast ambiguities in the `CXXExtraPass` instead of the frontend.
> Resolve cast ambiguity in C++ frontend

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Reference.kt
Otherwise, an update in the base's type could propagate to a member and this is BAD. This is due to the fact that
- a `MemberExpression` is also a `Reference`
- we have a PARTIAL DFG from the base of the member expression to the member expression
> Only propagate type updates in a `Reference` from FULL previous DFG nodes

- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt
Fixes #1472 .
The StackOverflow occurs because the class implements an interface with the same localName but in another package. Thus, we should consider the FQN when generating a type (if available). Same probably holds for the RecordDeclaration where we have somehow only used a local name so far? The change in `typeOf` itself is sufficient to prevent the StackOverflow but I'm not sure if these changes could have an impact on something else (i.e. the `TypeResolver`)?
> Use qualified names for types and record declarations

- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.kt
- cpg-language-java/src/test/resources/compiling/RecordDeclaration.java
Fixes #1548 by implementing the proposed measures. However, `handleFieldDeclaration` now only returns the last field/variable which is declared in a multi-field-declaration statement but since we never use the return value in this case, it should be fine.
> Java frontend: Handle multi-field-declaration statements

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TranslationUnitDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/WalkerTest.kt
- cpg-language-java/src/test/resources/Issue1459.java
We use `EOGStarterHolder`s to identify possible start nodes of the EOG. However, they might also be located in the middle of an existing EOG which means that some visitors would visit them multiple times and potentially even out-of-order. One example is the `SymbolResolver` which also led to #1459. We check that we only start the EOG-iteration/walking for nodes which are not in another EOG (i.e., we only visit nodes which actually serve as an entry-point).
Fixes #1459
> Filter eogstarters which do not start the eog

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/UnreachableEOGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/c/symbol_resolver_fail.c
This PR fixes a rather intricate bug in the subgraph walker that made the symbol resolver not resolve / "reach" all the necessary nodes. I took this opportunity to remove some legacy code from the class and also clean it up a lot.
In theory this should also make it a little bit faster because we do a little less stack pushing / peeking than before, but this is probably not noticeable.
> Cleanup of `SubgraphWalker`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/c/switch_eog.c
Not sure, if this really the "correct" solution. @konradweiss should probably have another look at this.
Fixes #1568
> Trying to fix switch EOG

- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclarationHandler.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/cxx/extern_c.cpp
It seems we previously ignored it, which meant that all code that was behind `extern "C"` was ignored.
Fixes #1578
> Parsing `CPPASTLinkageSpecification`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/InferenceConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
Otherwise inferred records with an FQN end up in global scope, which does not make sense.
> Trying to infer namespace when trying to infer records

- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
Fixes https://github.com/Fraunhofer-AISEC/cpg/issues/1432 (again)
> Do not depend on `JavaImportResolver` in cpg-neo4j

- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CPPLanguage.kt
`.c++` is also sometimes used for c++ source files.
> Add .c++ as file extension for cpp language

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/ImportDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/neo4j/SimpleNameConverter.kt
- cpg-neo4j/build.gradle.kts
- cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Neo4JTest.kt
The `ImportDeclaration` was trying to use the `Name` class without a converter, but unfortunately, we cannot add the prefix to the converter, so having three converters in the same file would override all properties.
Therefore, we are simply converting `alias` and `import` to a string.
> Fixed Neo4J import of `ImportDeclaration`

- cpg-all/build.gradle.kts
- cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/CpgConsole.kt
- cpg-console/src/test/kotlin/de/fraunhofer/aisec/cpg/console/ConsoleTest.kt
- gradle/libs.versions.toml
It seems that the kotlin shell is not (yet) compatbile with Kotlin 2.0. However, it seems that we can just use the scripting host from Kotlin 1.9 and it seems to work.
Fixes #1591
Related to https://github.com/Kotlin/kotlin-interactive-shell/issues/131
> Using Kotlin 1.9 for cpg-console

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/ArgumentHolder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/ExpressionBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/HasInitializer.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/DoStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/IfStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/ReturnStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/WhileStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/AssignExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/BinaryOperator.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CastExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/ConditionalExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/InitializerListExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/KeyValueExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/MemberExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/SubscriptExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/UnaryOperator.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/ArgumentHolderTest.kt
This adds a small utility function to `ArgumentHolder`, so we can check if an expression is part of their "arguments".
> Added `hasArguments` to `ArgumentHolder`

- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXExtraPass.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/c/cast_to_inferred.c
This is more a band-aid, than an actually "healing". The issue is that we often use the `language` to get a translation context in passes. But (sometimes) the language does not have it, since it is created using `registerLanguage` even before a translation context exists.
In an attempted fix, I am now using the translation context of a different node, but we should really think about how to deal with that in the future.
Fixes #1617
> Fixed crash in `CXXExtraPass::convertOperators`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilderTest.kt
Slightly inspired by discussion with @konradweiss. This adds a helper function to set the ast parent in cases where the node cannot be created within the `withChildren` block.
> Added a `withParent` helper function

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManagerTest.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CPPLanguage.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXAmbiguitiesTest.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolverTest.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguage.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/JavaCallResolverHelper.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/DeclarationHandler.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/ExpressionHandler.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguageFrontend.kt
- cpg-language-ruby/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ruby/RubyLanguage.kt
Lot of cleanups and removal of deprecated / legacy functions:
- Better integration of legacy call resolving by removing some duplicated code from the old call resolving functionality and instead providing a `legacyCandidates` set that can be supplied to `ScopeManager::resolveCall`
- Removed `ScopeManager::resolveFunctionLegacy`, as it was only used in one test and not used by the code base anymore
- Removed `SymbolResolver::resolveReferenceCallee` and `SymbolResolver::resolveMemberCallee` because (almost) all functionality was already implemented in `SymbolResolver::resolveCalleeByName` (which will stay for now)
- Removed `SymbolResolver::getInvocationCandidatesFromRecord` as it was only used by C++ and its functionality is also replaced by `SymbolResolver::resolveCalleeByName`
- Removed …
> Better integration of legacy call resolution with the new system and more cleanup

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandlerTest.kt
- cpg-language-python/src/test/resources/python/arguments.py
> Supporting `posonlyargs` in Python

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/DeclarationBuilder.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandlerTest.kt
- cpg-language-python/src/test/resources/python/varargs.py
Implements `vararg` support for python. This partially fixes #1653.
> Handling varargs in Python

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/Python.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandlerTest.kt
- cpg-language-python/src/test/resources/python/async.py
I'm a bit undecided whether or not I like this:
Pro:
- less duplicate code
Con:
- we break the strict 1:1 mapping of Python's ast classes to Kotlin classes in `Python.kt`. This was one of the design goals... @oxisto Is there a smarter kotlin way to not have the extra classes & relationship in Python.kt and still remove the duplicate code?
> Python: merge async with non-async code

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/Pass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ProgramDependenceGraphPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ReplaceCallCastPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/configuration/ExecuteBefore.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/configuration/PassOrderingHelper.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
* Removes dependency to DFG pass from GoExtraPass
* Added dependency to type resolver in GoExtraPass
* Adds dependency to dynamic invoke pass to PDG
* Makes soft dependency the default for ExecuteBefore. Also names soft to softDependency to be consistent with ExecuteBefore
> Some improvements to pass annotations

- cpg-all/build.gradle.kts
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TypeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Name.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ReplaceCallPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveCallExpressionAmbiguityPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CPPLanguage.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXExtraPass.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguage.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/ExpressionHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/Python.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
This PR extends the functionality of the `ReplaceCallCastPass` to also replace calls into construct expressions for languages, where we cannot differentiate between them in a frontend.
This also removes a symbol resolver check from the python frontend.
> Extending functionality of `ReplaceCallCastPass` to `ResolveCallExpressionAmbiguityPass`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
Since the prev/nextDFG edges are mirrored, clearing them manually is actually triggering an exception now. This removes the manual removal.
> Fixes `ConcurrentModificationException`

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/ExpressionHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
Someone started to include URLs in the doc strings for some reason. This PR fixes the broken URLs. We should probably also include URLs for all the other functions if this is something we'd like to have...
> fix doc string urls

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/EdgeList.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeList.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/EdgeListTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeListTest.kt
This adds support for adding nodes at a specific location in an unwrapped edge list.
> Added `add(index, element)` for `UnwrappedEdgeList`

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/Python.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
This PR removes a TODO we had in the code, where our class `excepthandler` was both the base "interface" as well as the concrete AST node. This splits up both, similar to `ast.stmt` and other cases.
> Implemented base class for `ExceptHandler`

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
This PR makes sure we open a new (block) scope for the function body. This is not a 1:1 mapping to python scopes, since python only has a "function scope", but in the CPG the function scope only comprises the function arguments, and we need a block scope to hold all local variables within the function body.
> Open a block and function scope for python functions

- .github/workflows/build.yml
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
- codecov.yml
- cpg-all/build.gradle.kts
- gradle/libs.versions.toml
Replacing sonarqube with codecov for coverage. Seperate PR for detekt will follow. This also aligns CPG with Codyze.
> Switching to codecov for code coverage

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/annotations.py
This fixes at least most of the errors when parsing glance. Fixes #1749
> Improved annotation parsing in python

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/StatementBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/LookupScopeStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/StatementBuilderTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/ScopeTest.kt
This PR adds a new node type `LookupScopeStatement`, which can be used to adjust the lookup scope of symbols that are resolved in the current scope. Most prominent examples are Python's `global` and `nonlocal` statements. There is also potentially a `global` statement in PHP, although we do not support that language.
Potentially, this could be re-used to for concepts that are similar in other languages as well.
Support for python will be added in a later PR. This will only add the node and provides the basic functionality in the lookup.
> Added a `LookupScopeStatement` node

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManagerTest.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
- docs/docs/CPG/impl/index.md
- docs/docs/CPG/impl/scopes.md
- docs/docs/CPG/impl/symbol-resolver.md
- docs/mkdocs.yaml
This PR renames `findSymbols` into `lookupSymbolByName` as a more appropriate name, because it lookups a symbol by its name.
It also adds the appropriate documentation about symbol lookup.
Fixes #1767
> Rename `findSymbols` into `lookupSymbolByName`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CPPLanguage.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguage.kt
This is needed in preparation for #1777 to better handle access to fields/members of a class when an implicit receiver is used.
> Added language trait `HasImplicitReceiver`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/Type.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/InferenceHelper.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/PassHelper.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonAddDeclarationsPass.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-typescript/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/typescript/TypescriptLanguageFrontendTest.kt
Unfortunatly, this cannot really be split into smaller pieces. It basically does the following:
- Move all inference related functions out of the symbol resolver and into a separate helper file
- Remove unnecessary calls to resolve member expressions in handleReference
I can try to add the needed language trait in a separate PR (see #1778). This also needs smaller adjustments in the python and typescript frontend. Mostly tests that previously asserted the "wrong" thing, are now asserting the correct resolution.
Fixes #1769
> Cleanup of `SymbolResolver`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/RegionUtils.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/unicode.py
> Fixed crash in `getCodeOfSubregion`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TypeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveCallExpressionAmbiguityPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXExtraPass.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXExpressionTest.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
This adds two new functions `ScopeManager.lookupUniqueTypeSymbolByName` and `Reference.doesReferToType`. This harmonizes a lot of boilerplate code in type resolver, cxx extra pass and resolve ambuigity pass, which were all trying to achieve the same thing.
Fixes #1766
> Add new function `lookupUniqueTypeSymbolByName`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
Previously, the old node still had all the type observers, which meant that the nodes registered as observers did not get any updates. Instead, we now unregister all nodes from the old one and register them as type observers for the new node. Maybe we need to make this configurable instead of the default? We definitely need it when we replace call nodes int cast/construct expressions - but we might not need it for other cases.
> Make sure to move `typeObservers` from old to new node when replacing nodes

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
Otherwise, we override the code/location again.
> `implicit()` only triggers code/location update now if its not empty

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
Named expressions in Python use `:=` as operator. Therefore we need to include it in the language definition. Otherwise, the `access` value of a reference will not be set correctly.
> Added `:=` as simple operator in Python

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Component.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Reference.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/FluentTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolverTest.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
This PR establishes a dependency graph between translation units using their import declarations. This enables the symbol and import resolver to leverage this information to resolve symbols in an ordered way so that translation units that are depended on are resolved first.
> Resolving imports and symbols according to import dependencies

- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
> Added `JVMLanguage` to the list of registered languages in `cpg-neo4j`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlDependenceGraphPass.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/1740_endless_cdg_loop.py
When generating the CDG, we had a cycle because we accepted smaller states as "unique" when lifting up some stuff after the EOG iteration. This doesn't make sense and is fixed by improved checks.
Fixes #1740
> Fix cycle in CDG pass

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/FunctionScope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/Statement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Block.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/statementHandler/StatementHandlerTest.kt
- cpg-language-python/src/test/resources/python/nested_functions.py
Nested functions have not been added to the AST because they occur inside a `BlockScope` but the `Block` only accepted `VariableDeclaration`s as locals. This is not correct and has been extended to `ValueDeclaration` which also covers the `FunctionDeclaration`.
Fixes #1736
> Handle nested functions

- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/StatementHandler.kt
Replaces the usage of a `UnaryOperator` with operatorCode "throw" with the new node `ThrowStatement` in the java frontend.
> Replace UnaryOperator("throw") with ThrowStatement for java

- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/StatementHandler.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CompressLLVMPass.kt
- cpg-language-llvm/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguageFrontendTest.kt
Replaces the usage of a UnaryOperator with operatorCode "throw" with the new node ThrowStatement in the LLVM frontend.
> Replace UnaryOperator("throw") with ThrowStatement for LLVM

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
- docs/docs/CPG/specs/eog.md
Currently, the `EvaluationOrderGraphPass` handles the `UnaryOperator` with operatorCode "throw" as a throw expression. Since all frontends have been migrated to use the `ThrowExpression`, this is obsolete. The eog-spec-file is updated and the pass too.
Closes #1817
> Remove `UnaryOperator` used as throw from EOG pass and spec

- cpg-language-llvm/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguageFrontendTest.kt
Testing is very important but the LLVM tests do not meet the styleguides which have recently been suggested in #1743. This PR updates them to meet the requirements.
> Update LLVM tests to match new styleguide

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/RegionUtils.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/ExpressionHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
It seems that region utils (whatever they do) checked for a potential new line character in every call of `codeAndLocationFromChildren`. But the new line char should stay constant within the file, so we are using the `lineSeperator` property (in the python frontend) instead.
> Optimized region utils

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
Reworks extensions following prev/next DFG and EOG and also adds CDG- and PDG-following functions. Both new functions feature an optional interprocedural analysis which explores the callgraph.
Since there was a bunch of redundant code, the iteration was merged into a single method and only the way in which to collect the next step has to be provided by the respective specialized subgraph-following-methods.
> Rework extensions to follow subgraphs

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
Improves debugability by using `when` instead of custom handling map and dispatching function. Users have to order the when options such that more specific `is` check does not get shadowed by the more general check for its super class. However, modern IDEs can warn of such "unrechable" cases
> EOG: `when` instead of custom dispatcher

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/BinaryOperator.kt
Unlike other nodes, this node is missing the "location" property in toString.
> add location to BinaryOperator.toString()

- cpg-language-python/build.gradle.kts
No need to expose jep's API to CPG users.
> change jep dependency from api to implementation

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/Query.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
More homogeneous interfaces of the `followX...` extensions, and more functions which follow the edges until the end (without condition)
> Add more extensions to follow edges until the end

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TypeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManagerTest.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/DeclarationHandler.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/DeclarationHandler.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/ExpressionHandler.kt
- cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonAddDeclarationsPass.kt
Currently, the symbol resolver runs wild and considers all nodes of all languages. When we have more instances where we have multiple languages in the same component, this craates a problem.
This PR now only considers the same language as the ref we are looking for.
> Restrict symbol resolving to language

- cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/TranslatePlugin.kt
- cpg-language-ini/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ini/IniFileFrontend.kt
- cpg-language-ini/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ini/IniFileLanguage.kt
- cpg-language-ini/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/ini/IniFileTest.kt
- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
Fix the package name to align with the other frontends and enable the INI frontend in the console and neo4j modules.
> fix package name and enable ini in console and neo4j

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclarationHandler.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/types/TypedefTest.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontendTest.kt
- cpg-language-cxx/src/test/resources/c/typedef_struct.c
- cpg-language-cxx/src/test/resources/cxx/typedef_struct.cpp
- cpg-language-cxx/src/test/resources/typedefs/weird_typedefs.cpp
Still not 100 % perfect, but it is as close as we can get because the CDT does not give us this information.
> Better detection of typedefs in C++

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Literal.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/persistence/Common.kt
Fixes issues with python interface files
> Persisting literal values more conservativly

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
This introduces a new extension function `ImportDeclaration.updateImportedSymbols`. The idea behind that is that we might need to update the `importedSymbols` of an import declaration, if the symbols that "live" in the associated namespace change. This is mainly the case once we infer records out of known `Type` nodes. Therefore, the type resolver will update all the imported symbols before executing all the remaining passes. This way, the remainder of the passes can access imported symbols that were inferred.
Needed for #1862
> Providing an API to update the imported symbols for an `ImportDeclaration`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
This adds a new function `Language.bestViableReferenceCandidate` which takes the old implementation as a default behaviour.
> Provide a function for languages to influence reference resolution out of candidates

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/testFixtures/kotlin/de/fraunhofer/aisec/cpg/test/TestUtils.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaCallResolverHelper.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguage.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/JavaExtraPass.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/calls/SuperCallTest.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/java/StaticImportsTest.kt
This PR consists of a major overhaul of Java reference and member expression parsing. It removes a LOT of old weird legacy code that was full of weird things.
It also introduces a new Java-specific pass, that takes care of deciding when a member access is actually static or not. This might be something that we could decide to adapt for other/all languages (maybe also tied to the discussion in #1863).
> Fixing Java field access

- buildSrc/src/main/kotlin/cpg.frontend-dependency-conventions.gradle.kts
Currently, the depenendency injected frontends are `api` dependencies. That means that published artefacts that dynamically depend on the configured frontends (such as Neo4J) publish all frontends as a dependency. That was not the intention. Instead they should contain no external dependencies to frontends and rather use the frontends that are available when the user loads them in.
> Demote frontend dependencies to `implementation`

- cpg-neo4j/build.gradle.kts
This PR is a follow-up to #1926 (which did not work). This time we ressort to patching the dependency out of the POM.
> Patching dynamic dependency to frontends out of `cpg-neo4j` POM

- cpg-neo4j/build.gradle.kts
The C++ frontend is a dependency for the neo4j integration tests. However, that is never explicitly specified. The reason for that is we cannot use the regular ´project("cpg-language-cxx")` syntax because if the C++ frontend is disable, the "cpg-language-cxx" project does not exist. We therefore now use `findProject` to find it first and it if its there.
> Adding C++ frontend as 'optional' integration test dependency to Neo4j

- buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
This PR adds back the heap size to the test, which was lost in #1925
> Adds back test heap size

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
This silences a lot of warnings. We are using `handleDefault` instead, which adds it to the EOG, but does not add any children nodes.
> Handling `ImportDeclaration` in EOG

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/processing/strategy/Strategy.kt
This PR adds two configuration option to the `SymbolResolver`:
- `skipUnreachableEOG` skips unreachable EOG paths when iterating the EOG. This means that symbols on unreachable EOG paths are not resolved. This can speed up resolution when large parts of a file are not reachable (e.g., because they are guarded by a platform switch)
- `ignoreUnreachableDeclarations` will check, whether a declaration that is a candidate for a symbol is on an EOG path that is unreachable. This is useful in dynamically invoked languages, where symbols are declared differently on different paths.
> Adding options to handle unreachable EOG branches in the `SymbolResolver`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveMemberExpressionAmbiguityPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManagerTest.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclaratorHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonAddDeclarationsPass.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/statementHandler/StatementHandlerTest.kt
This PR speeds up type and symbol resolution across the whole code-base
* Optimized `extractScope` by using the `fqnScopeMap` instead of filtering ALL scopes.
* Removed unnecessary nested loop over all nodes/types again in `TypeManager`
* Faster type/scope merging in the `TranslationManager` the using parallel parsing (8ms instead of 5s)
* Do not try to resolve member expressions of an unknown base type. This will fail and will only result in a lot of spam and in the attempts to resolve the "UNKNOWN" scope (which does not exist)
This boosted my test case (parsing python type shed stdlib) from ~70s to ~~45s~~ 32s
> Faster type and symbol resolution

- .github/workflows/build.yml
- README.md
- build.gradle.kts
- buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
- codyze-compliance/build.gradle.kts
- jitpack.yml
This PR enables automatic publishing of CPG modules as [GitHub Maven Packages](https://github.com/orgs/Fraunhofer-AISEC/packages?repo_name=cpg). This works infinitely better than using JitPack, since we are in complete control of the publishing process and we can already publish them as part of the CI build, so it is immediately available. By default, all commits on the `main` branch will be published as `main-SNAPSHOT`. If a PR has the label `publish-to-github-packages`, it will also be published. This has the added bonus, that the groupId stays the same, one only needs to add another repository, so one can freely switch back to a released version on Maven Central.
See https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#using-a-publ …
> Trying to publish to GH packages

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/foobar.py
This PR parses the `@staticmethod` annotation and does not take accidentilly put in a receiver in this case.
> Resolving calls to static python methods correctly

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationResult.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Component.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/builder/Fluent.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/MeasurementHolder.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageTest.kt
- cpg-core/src/testFixtures/kotlin/de/fraunhofer/aisec/cpg/test/TestUtils.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontend.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontend.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoUtils.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/IntegrationTest.kt
- cpg-language-ini/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ini/IniFileFrontend.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/JavaExternalTypeHierarchyResolver.kt
- cpg-language-jvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/jvm/JVMLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/big-project/component1/mypackage/module.py
- cpg-language-python/src/test/resources/python/big-project/component2/otherpackage/module.py
- cpg-language-python/src/test/resources/python/big-project/stdlib/os.pyi
This PR introduces the possibility to specify *one* top level *per* component instead of just a global one. This introduces a new `topLevels` builder in the `TranslationConfiguration`. The single `topLevel` flag is still there and sets the top level of the default component ("application"). The top level can be fetched via a virtual property `topLevel` in the `Component` class.
I also added a python test that parses different components to demonstrate the API.
Fixes #1959
> Support different top levels for each component

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/big-project/component1/mypackage/module.py
- cpg-language-python/src/test/resources/python/big-project/component2/otherpackage/module.py
Previously, this information was lost because we were only copying/moving the nodes and not the edges
> Keep argument name information when converting member call expressions to call expressions

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/Query.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryTree.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/QueryTest.kt
- Use `stringRepresentation` for `toString()`
- Introduce a `node` property (naming to be discussed) that holds a reference to the node that is usually displayed in the string representation
> Make QueryTree more beatiful

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/flows/Dataflow.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonAddDeclarationsPass.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/DFGTest.kt
- cpg-language-python/src/test/resources/python/tuple_assign.py
> Support tuple deconstruction and follow value flows based on index

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonAddDeclarationsPass.kt
The `PythonAddDeclarationsPass` infers a `FieldDeclaration` even if we're in a static function. This is not really correct. We now infer a `VariableDeclaration` instead.
> Do not infer field declarations in static methods

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXIncludeTest.kt
#1960 introduced a bug when using the unity build mode without software components.
I'm not sure why the `run`  is need for the else case of the `let`, but it fixes the problem.
I also added a test-case for the unity build mode (with and without software components).
> Fix unity build

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/DFGTest.kt
- cpg-language-python/src/test/resources/python/context_sensitive.py
I am not sure if this really solves *all* the problems, but at least this tries to use the information that we have in the calling context in/out so that we are properly following dataflows into functions and out of functions using the correct call (stack).
> Basic implementation of following context-sensitive calls in `followNextDFGUntilHit`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/DeclarationBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/TypeBuilder.kt
> Rename `localNameOnly` to `doNotPrependNamespace`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveMemberExpressionAmbiguityPass.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
Previously, we were re-using the (partial) name of the expression instead of the FQN. This has led to some unexpected results, in a way that later passes could not resolve the type of the reference (or call expression).
> `ResolveMemberExpressionAmbiguityPass` now correctly set an FQN in its replaced references

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeList.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/flows/Invoke.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/flows/InvokeTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/persistence/TestCommon.kt
This PR adds a mirrored `calledBy` edge in a `FunctionDeclaration` that mirrors the `invokes` edge of a `CallExpression`.
> Added `calledBy` mirrored edge in `FunctionDeclaration`

- codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/Sarif.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
As discussed here: https://github.com/Fraunhofer-AISEC/cpg/pull/1999#discussion_r1936926974
> Refactor firstParentOrNull to accept type parameter and optional predicate

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/PassHelper.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.kt
This PR performs a clean up of the `ScopeManager` especially related to how we handle member resolution, which was still a left over from the "legacy" system. 
This makes all the necessary handle functions `open` so that someone external to this library can extend and replace this pass, if needed. Furthermore, we make all functions we do NOT wish to be overriden `private` (mostly because we consider them part of a legacy API).
Furthermore, this PR adds more documentation to this pass.
> Cleanup `SymbolResolver` and make it more extensible

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationResult.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Component.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/Pass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/processing/strategy/Strategy.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/FluentTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolverTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/processing/VisitorTest.kt
This PR makes the same import-dependencies object that is currently available on a `Component` (between TUs) available on the `TranslationResult` (between components). I decided to generalize the `ImportDependencies` class for this. This might sounds overkill but my feeling is that this might pay off at some point.
To access that information, I added two new "strategies" (`TRANSLATION_UNITS_LEAST_IMPORTS` and `COMPONENTS_LEAST_IMPORTS`). I do not really like the UPPERCASE naming on these strategies, but we probably want to change that for all of them at some point. So they are named like this for consistency.
Furthermore, `ComponentPass` passes are now executed according to the `COMPONENTS_LEAST_IMPORTS` strategy and a `TranslationUnitPass` is executed according to first the …
> Execute `ComponentPass` passes according to the dependencies between components

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SystemInformation.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SystemInformationTest.kt
Separate PR for the changes from #2019 which are useful but no longer required for the functionality of #2019. In particular, we can compare `VersionInfo` class and refactor the code parsing it.
> Python `VersionInfo` extension

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/DeclarationBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/ImportDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/ParameterDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeSet.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/scopes/Import.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/NamespaceScope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/StructureDeclarationScope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/ValueDeclarationScope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveMemberExpressionAmbiguityPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolverTest.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXLanguageFrontend.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclarationHandler.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/SpecificationHandler.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/import_test.py
- cpg-language-python/src/test/resources/python/import_vs_member.py
Unfortunately this PR is beginning to grow into something too big, so we probably want to merge it soon, but the problem is that things in the import / scope system are really tightly coupled. Hopefully a few things are now more de-coupled.
* Instead of caching `importedSymbols` statically once (or twice), instead we resolve the import declaration back to the namespace (declaration) and update the symbol on-chance. This still not the perfect solution that I want, but it's  a step into the right direction.
* This also speeds up the `ResolveMemberExpressionAmbiguityPass`.
* Rework `resolveParentAlias` to take scope information into account
> Various improvements to the import system

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveCallExpressionAmbiguityPass.kt
The PR adds the `argumentEdges` when replacing a `CallExpression` to a `ConstructExpression` ensuring that the names are also adopted
> Add `argumentEdges` to ResolveCallExpressionAmbiguityPass

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/flows/EvaluationOrder.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/flows/EvaluationOrderTest.kt
This adds two new extension functions `insertNodeBeforeInEOGPath` and `insertNodeAfterwardInEOGPath` that insert a new node into an existing EOG path either before or after the node of reference.
> Added functions to insert a node in an existing EOG path

- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/DeclarationHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/ExpressionHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/Python.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
We consider some python nodes to be "declarations" and this PR splits off processing these into a dedicated `DeclarationHandler`, rather than having them in the `StatementHandler`.
> Extracting handling of python "declarations" into `DeclarationHandler`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TypeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Name.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/GlobalScope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManagerTest.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/DeclarationHandler.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/SpecificationHandler.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/superclasses/incorrect.py
This should hopefully fix all type (name) confusions. This is a major rework of the `ScopeManager::extractScope` function that should be faster and produce less overhead and is also iterative instead of recursive.
Incidentally, the new "more correct" behaviour also uncovered some already existing problems in some other language frontends.
> Major rework of `ScopeManager::extractScope`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/PassHelper.kt
Not having the restriction leads to confusion when we have a namespace in different languages. As a nice effect, I had a look at things that were for some reason nullable and made them non-nullable.
> Restricting `lookupScopeByName` to a specific `language`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/MermaidPrinter.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/processing/strategy/Strategy.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/MermaidPrinterTest.kt
This PR adds a direction parameter to `printDFG`, enabling control over the DFG direction to follow.
It also adds back `printEOG` and adds a new `printAST` that uses the same technique
> Make `printGraph` configurable with a `Strategy`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/PassHelper.kt
Currently, we use the global scope's `astNode` as a start node for inference of "global" things. However, this is very buggy, since the `astNode` of the global scope is assigned to the last TU we parse. If this TU was parsed in another language, we can run into situations where we infer things in the wrong language. 
This PR fixes that by introducing a new `Language::translationUnitForInference` function that defaults to the first TU in a component and can be used by a language to provide a specific TU for specific declarations.
> Providing a `Language::translationUnitForInference` function that is used for global inference

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/UnreachableEOGPass.kt
- cpg-language-python/build.gradle.kts
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonUnreachableEOGPass.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonValueEvaluatorTest.kt
This PR adds a special version of the `UnreachableEOGPass` to the python frontend. It is executed before the symbol resolver and uses the python value evaluator.
> Using `UnreachableEOGPass` in python

- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/ConceptPass.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/flows/cxx/CXXEntryPointsPass.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/memory/cxx/CXXDynamicLoadingPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DynamicInvokeResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveCallExpressionAmbiguityPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveMemberExpressionAmbiguityPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/StatisticsCollectionPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXExtraPass.kt
- cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
- cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/JavaExtraPass.kt
- cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/WalkerTest.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonAddDeclarationsPass.kt
This PR makes the "node" part of the `registerHandler` of the walker non-nullable, as it is non-nullable. This was leading to annoying code with unnecessary null checks. Also converted the `TriConsumer` to a Kotlin function signature that allows the identification of the individual elements of the handler.
> Make node of registerHandler non-nullable

- cpg-neo4j/build.gradle.kts
- gradle/libs.versions.toml
The dependency netty-handler contains a Vulnerability that I would like to patch temporarily until `[neo4j-java-driver](https://github.com/neo4j/neo4j-java-driver)` updates the dependency internally. 
Netty, an asynchronous, event-driven network application framework, has a vulnerability starting in version 4.1.91.Final and prior to version 4.1.118.Final. When a special crafted packet is received via SslHandler it doesn't correctly handle validation of such a packet in all cases which can lead to a native crash.
> Update transitive dependency due to vulnerability

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/nested_replace.py
There was a bug in `translationUnitForInference` where we returned an incorrect translation result.
> Fixed bug in `translationUnitForInference`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveMemberExpressionAmbiguityPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/resources/python/import_vs_member.py
In some some languages, we have an ambuigity when calling `a()` whether this is a local function or imported from another namespace. The symbol resolver already resolves this correctly, but leaves the call expression's name as is. This is inconsistent with what the `ResolveMemberExpressionAmbiguityPass` does, which is adjusting the name of a dotted call `a.b()` to whatever the real import name is.
This pass harmornizes the name of `CallExpression` nodes when they are imported from another package in the `SymbolResolver`.
> Harmonizing `CallExpression` name's when importing from another namespace

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
All references are normalized against alias imports. Thus, we have to check against the imported symbol and not the imported name.
TODO:
-[ ] Fix Python test (issue with normalizing an aliased call)
> Fix: importedFrom now checks the import instead of name

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
It seems that sometimes `source.scope?.astNode?.component` is null and I added a fallback to definitly get a component.
> Added fallback for `translationUnitForInference`

- codyze-core/build.gradle.kts
- codyze-core/src/integrationTest/kotlin/codyze/SarifTest.kt
- codyze-core/src/integrationTest/resources/simple.py
- codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/Sarif.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/FlowQueries.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/DataflowQueriesTest.kt
- cpg-concepts/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/concepts/MemoryTest.kt
It seems that the verbose flag in the DFG and EOG analysis functions was true per default so the analysis type (MAY or MUST) had no effect. This cluttered the SARIF output.
> Removing `verbose` of `dataFlow` and `executionPath`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationContext.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
This PR fixes some issues with parsing of additional sources. The main problem was that if include parts are "sister" paths, e.g., ../external/lib1 and ../external/lib2, then the previous logic return an incorrect relativ path of ../lib2 instead of "lib2". This PR changes that and optimizes the implementation in a way that the additional sources are already prepared in a relative way in the translation manager (the original include path is kept to be sure). This way, a language frontend can just focus on looking at relative paths and see whether they match for example a package structure.
> Fixed issues with parsing additional sources

- cpg-neo4j/build.gradle.kts
- gradle/libs.versions.toml
removing the manual fix of the transitive netty dependency after the neo4j bolt driver updated this dependency.
> Update to neo4j bolt driver by minor version after critical fix

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/UnreachableEOGPass.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/Query.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryTree.kt
- cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/QueryTest.kt
- cpg-concepts/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/concepts/ConfigurationPassTest.kt
- cpg-concepts/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/concepts/DynamicLoadingTest.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/config/python/PythonStdLibConfigurationPass.kt
- cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/NullPointerCheck.kt
- cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/OutOfBoundsCheck.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/evaluation/MultiValueEvaluator.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/evaluation/NumberExtensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/evaluation/NumberSet.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/evaluation/SizeEvaluator.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/evaluation/ValueEvaluator.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/EvaluationExtensions.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/evaluation/MultiValueEvaluatorTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/evaluation/SizeEvaluatorTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/evaluation/ValueEvaluationTests.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/evaluation/ValueEvaluatorTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/MermaidPrinterTest.kt
- cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonValueEvaluator.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonUnreachableEOGPass.kt
This PR moves `ValueEvaluator` to `cpg-core` and makes it possible for a language to override the default.
> Moving `ValueEvaluator` to `cpg-core`

- .github/workflows/build.yml
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/codyze.module-conventions.gradle.kts
- buildSrc/src/main/kotlin/cpg.application-conventions.gradle.kts
- buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
- buildSrc/src/main/kotlin/cpg.formatting-conventions.gradle.kts
- buildSrc/src/main/kotlin/cpg.frontend-conventions.gradle.kts
- buildSrc/src/main/kotlin/cpg.library-conventions.gradle.kts
- buildSrc/src/main/kotlin/cpg.publishing-conventions.gradle.kts
- codyze-compliance/build.gradle.kts
- codyze-core/build.gradle.kts
- codyze/build.gradle.kts
- cpg-analysis/build.gradle.kts
- cpg-concepts/build.gradle.kts
- cpg-console/build.gradle.kts
- cpg-core/build.gradle.kts
- cpg-language-cxx/build.gradle.kts
- cpg-language-go/build.gradle.kts
- cpg-language-go/src/main/resources/.gitignore
- cpg-language-ini/build.gradle.kts
- cpg-language-java/build.gradle.kts
- cpg-language-jvm/build.gradle.kts
- cpg-language-llvm/build.gradle.kts
- cpg-language-python/build.gradle.kts
- cpg-language-ruby/build.gradle.kts
- cpg-language-typescript/build.gradle.kts
- cpg-neo4j/build.gradle.kts
- gradle/libs.versions.toml
We migrated to the new https://central.sonatype.com portal with our namespace and we had to change the plugin to the new modern version of https://github.com/vanniktech/gradle-maven-publish-plugin
This also should now include skipping dokka/javadoc for GitHub package releases.
> Maven publish with new plugin

- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/file/python/PythonFileConceptPass.kt
The `PythonFileConceptPass` is slightly improved as follows:
* It generates an equal `ReadFile` operation only once. Somehow, there were multiple equal nodes created. Apparently, the same node is visited multiple times.
* The `followDFGEdgesUntilHit` can be configured with `findAllPossiblePaths = false` which should simply merge two paths instead of following them separately. The important part is that all end-nodes should still be collected but we will explore less paths reaching it.
> Small improvements to `PythonFileConceptPass`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/TypeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/ReturnStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/DynamicType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/FunctionType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/HasType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/types/TypeTest.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/DeclarationHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/ExpressionHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonAddDeclarationsPass.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/TypeTest.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/statementHandler/StatementHandlerTest.kt
- cpg-language-python/src/test/resources/python/dfg_type.py
- docs/docs/CPG/impl/types.md
- docs/mkdocs.yaml
This PR introduces a new `Type`,  the `DynamicType`. It is needed for programming languages that do not have static typing, such as TypeScript or Python. In these languages, the type is determined at run-time. Therefore, neither of our existing `AutoType` or `UnknownType` types completely catch the dynamics.
This PR adds the basic concept of the type itself and uses it very sparsely for function parameters, which previously were of `AutoType`.
> Introducing `DynamicType` and removing usage of `AutoType` from python

- codyze-console/src/main/webapp/package.json
- codyze-console/src/main/webapp/pnpm-lock.yaml
Not really a problem since we use a newer version internally but setting this explicit should silence dependabot.
> Upgrading cookie to get rid of annoying dependabot warnings

- .github/renovate.json
Weekly dependency updates should be more than enough, otherwise we will get spammed by npm updates.
> Changing renovate updates from `daily` to `weekly`

- codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/Sarif.kt
> Consistently displaying SARIF `level` and `kind` fields

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveCallExpressionAmbiguityPass.kt
- cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXExpressionTest.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
Somehow, replacing a node (here: `CallExpression`s) results in the ast children still pointing to the old parent even if they are now part of the new node. This PR sets this relationship manually. However, in the long-term, I'd encourage a different solution.
> Set AST parent to new node when replacing a node

- codyze-core/src/integrationTest/kotlin/codyze/SarifTest.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/GenericConceptBuilder.kt
This PR adds helper functions to easily create `Concept` nodes from string descriptions.
Required by
- #2200
- #2183
> Add helper functions for concept creation

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/FlowQueries.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/TypeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/ListType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/NumericType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/ObjectType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/StringType.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/Type.kt
- cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/LoadIncludesTest.kt
We need to understand which nodes on a DFG path have to be followed separately. This is highly specific to each language, so this is only a rough approximation which uses the following heuristics:
* Is the type of a node (i.e., operation and its result, reference, declaration) mutable? If not, we typically copy the data.
* Do we call constructors? This obviously generates a new object which should be handled separately from the previous ones.
* Do we use some specific constructs which are no constructors but have the same effect of generating a new object? An example are list/set/dict comprehensions.
To implement this, the types get an additional field `isMutable` which can/should be set appropriately. Currently, it is set to some defaults (`true` for `ObjectType`s, `false` for …
> Very simple version of memory tracking heuristics to understand if dataflows are split up and require following multiple paths

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TranslationUnitDeclaration.kt
- cpg-language-ini/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/ini/IniFileFrontend.kt
Remove `namespaces` and `includes` as a persisting field. Includes and namespaces are still in declarations and can be filtered for. Previously, namespaces and includes were included twice in fields that were persisted as AST nodes. Leading to these nodes to be reachable by two distinct AST edges, which contradicts the tree property.
Closes #2197
> Remove namespaces and includes as a persisting field. 

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ResolveMemberExpressionAmbiguityPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/PassHelper.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt
- cpg-language-python/src/test/resources/python/call_confusion.py
There was a bug in resolving member expression ambiguities when the name of a member's base was identical to an import. This PR should resolve that issue.
Fixes #2220
> Resolved bug in member expression ambiguity

- .github/workflows/build.yml
Seems to be the only one compatible with our Mac mini cluster.
> Choosing "corretto" JVM distribution

- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/file/python/PythonFileConceptPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/Pass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
Passes are currently instantiated for each "target" (e.g., a component or EOG starter). Therefore, the existing `cleanup` method can only clean the state of the current pass instantiation. But sometimes we need to clean "global" state that exists beyond multiple invocations but need to be cleaned before the next analysis. 
Therefore, this pass introduces a `finalCleanup` method which is called after all targets are handled. We call it on the pass prototype that we create before each target.
> Adding a `Pass::finalCleanup` method

- codyze-core/src/integrationTest/kotlin/codyze/SarifTest.kt
- codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/Project.kt
- codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/Sarif.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationConfiguration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationContext.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Component.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/sarif/PhysicalLocation.kt
- cpg-neo4j/src/main/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
This issues the component's name as a `uriBaseID` and relativizes paths to the component if possible. Also includes some more file/path related cleanups.
Fixes #2215
> Using relative paths in SARIF file

- cpg-concepts/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/concepts/file/FileConceptTest.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/Concept.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/Operation.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/arch/OperatingSystem.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/auth/Authentication.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/config/Configuration.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/Cipher.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/CipherOperation.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/DiskEncryption.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/file/File.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/flows/EntryPoint.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpClient.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpEndpoint.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/logging/Log.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/logging/LogWrite.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/memory/Memory.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/EOGConceptPass.kt
- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/file/python/PythonFileConceptPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/OverlayNode.kt
Instead `equals` now excludes the `underylingNode` and the EOGConceptPass collects intermediate states which are then merged into a final state and then uses `finalCleanup` to set the underlying node based on the state.
> Removing `equalWithoutUnderlying`

- cpg-concepts/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/concepts/file/FileConceptTest.kt
- cpg-concepts/src/integrationTest/resources/python/file/file_loop.py
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/functional/BasicLatticesRedesign.kt
If the EOG ended in a loop, we previously "forgot" to add to the final state.
> Fixed problem with `finalState` in `iterateEOG`

- codyze-console/src/test/kotlin/de/fraunhofer/aisec/codyze/console/ApplicationTest.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TranslationUnitDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeCollection.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeList.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeSet.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/EmptyStatement.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/LookupScopeStatement.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/NodeTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/EdgeListTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/EdgeSingletonListTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeListTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeSetTest.kt
- cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
This PR makes the node's `id` derive from its hash-code. This is probably not a 100 % solution, but it should do for those cases where we need an ID that persists beyond translations.
In the course of using hashcode this way, I discovered several problems with some hashcode implementations, such as in the unwrapped lists.
> Deriving ID from hashcode

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/assumptions/Assumption.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
This PR add a fix to the assume functions that makes them return the same type as the calling object. The past implementation would return `HasAssumptions` which obviously does not allow us to add `assume` without creating type issues. An additional example is added in form of an inference assumption.
The PR also ads a hashCode implementation for assumptions.
> Assumption Interface Fix and HashCode adaptation

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationResult.kt
I somehow experienced `ConcurrentModificationException`s in `MermaidPrinterTest.testPrintEOG()` which seem to come from the newly introduced dirty nodes system. This is somehow weird and I would question why this can happen in the first place. Any idea @oxisto ? Can you replicate this problem? To fix it (if we agree that it actually exists), I'd use a `ConcurrentHashMap` instead of a normal `HashMap` when marking dirty/clean nodes. I'm wondering if we also have to synchronize access to the list of passes for a dirty node
> Use `ConcurrentHashMap` to mark dirty and clean nodes

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/functional/BasicLatticesRedesign.kt
Two things happen in this PR:
* Return `Order.EQUAL` if two lattices are identical to save heavy computations
* Use `IdentitySet` and `List` when calculating key sets because anything else would lose equal but non-identical keys.
> Lattice Redesign fixes and performance

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/FlowQueries.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryTree.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/assumptions/Assumption.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/Edge.kt
Sets are more adequate for holding assumptions to avoid storing the same assumptions multiple times at a node or in a result object.
The `collectAssumptions` function allows for retrieval of all contained assumptions in the final result when the assumption holding object is a composite type, e.g., QueryTree that holds QueryTree, and does not force us to rewrite setters to copy assumptions every time we add a `HasAssumptions` implementing object to another `HasAssumptions` implementing object. The use of `collectAssumptions` in `addAssumptionDependences` helps with the propagation of assumptions in composite `HasAssumptions` types, e.g., QueryTree, NodeWithAssumption.
> Make assumptions a set and add collectAssumptions 

- cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/EOGConceptPass.kt
- cpg-concepts/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/TagOverlaysPassTest.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/RecordDeclaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/Pass.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/ExtensionTest.kt
This PR does two things:
- It considered (almost) all AST nodes in the `EOGStarterPass`, even though they have no "next" EOG. This way all AST nodes in the graph are at least reached once
- It considers the outcome of `handleNode` also in the "intermediate" initial states. Previously only nodes that were the target of an incoming EOG edge were handed to `handleNode`
> Consider (almost) all AST nodes in the `EOGStarterPass`

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/FlowQueries.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/assumptions/Assumption.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
Elaborates the documentation of the `assume` function to specify the format of the message parameter.
It also updates existing texts accordingly
Fixes #2275
> Specify what the text of assumptions should look like

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationResult.kt
Adds a map to the translation result that holds the status assigned to assumptions identified by a specific uuid when being set manually. The map is empty after a new analysis and can be filled during manual evaluation of assumptions. The Map will be used when an objects is decided(.decide()) to update the assumptions that are attached to the object.
> Adding map of uuid to assumptionstatus

- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/FlowQueries.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryStates.kt
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryTree.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/assumptions/Assumption.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Component.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/Edge.kt
This PR does the following:
- Uses the assumption statuses in the translation results to update the assumption status of a `QueryTree` before the decision process.
- Fixes a mistake, at least one IMO, in the decision logic.
- Collects all assumptions related to a `QueryTree`.
- Adds global assumptions that are attached to the `TranslationResult` and `Component` assumptions in the `collectAssumptions` of the Node class.
> Update AssumptionStatus and better assumption collection before decide

- cpg-analysis/build.gradle.kts
- cpg-analysis/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/query/FlowQueriesTest.kt
- cpg-analysis/src/integrationTest/resources/python/context.py
- cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/FlowQueries.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
This makes it possible to provide a flow query context to `dataFlow`, e.g., gathered by a previous step.
> Provide `ctx` to `dataFlow`

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/DeclarationBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/builder/Fluent.kt
This made our node IDs dependend on the analysis system.
> Made `name` of translation unit a relative path and not depending on the system

- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/Declaration.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/GlobalScope.kt
- cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/ObjectType.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/ScopeTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/types/ObjectTypeTest.kt
- cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/persistence/TestCommon.kt
This PR adds (virtual) properties to `ObjectType` to query methods, constructors and fields of a *Type*. Previously this was done via the `RecordDeclaration`.  However, this added confusion when languages declared methods and fields outside of the class construct itself. It was never clear whether to add fields and methods to the `fields` and `methods` property of a `RecordDeclaration`, which is actually an AST element.
This does not (yet) remove `fields` and `methods` from `RecordDeclaration`, this is done in a separate PR.
> Added API to return methods of a `Type`

- cpg-language-typescript/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/typescript/TypeScriptLanguageFrontend.kt
This follows
https://github.com/Fraunhofer-AISEC/cpg/blob/b9d16566cf0f381a883de36289a2a3515eb6ab13/cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoStandardLibrary.kt#L836
to unify the arch names
> Use correct arch detection in os.arch to fix #2407
