Fraunhofer-AISEC/cpg

.github/workflows/build.yml
Hopefully the latest CI-related fix now.
=> Removed sonar.branch.name to fix SonarQube PR analysis

README.md, build.gradle.kts
Added a paragraph about using the cpg library using jshell on the CLI to the README.
=> Added jshell to README

src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java, src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java, src/main/java/de/fraunhofer/aisec/cpg/graph/StaticCallExpression.java, src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
=> Introduce proper handling for static calls

src/main/java/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.java, src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java, src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/VariableResolverTest.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java, src/test/resources/variables/local_variables.cpp
correctly attach a variabledeclaration to its parent block, and not just to its parent node
=> Julian 16 wrong fields

build.gradle.kts, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationListHandler.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java, src/test/resources/components/ForEachStmt.java, src/test/resources/components/foreachstmt.cpp, src/test/resources/components/forstmt.cpp
- Added tests for Java/cxx for-each
- Added `spotlessApply` as a dependency of `compileJava` so it should now be automatically executed when building with recent IntelliJ versions.
=> Added even more tests

src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java, src/main/java/de/fraunhofer/aisec/cpg/helpers/RegionConverter.java, src/main/java/de/fraunhofer/aisec/cpg/helpers/TypeConverter.java
It will serialize
- the type as string representation
- the type modifier
- the type adjustments
Fixes #24
=> Modified type converter and moved all converters to helper package

src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/graph/BinaryOperator.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXSymbolConfigurationTest.java, src/test/resources/symbols.cpp
=> Added possibility to configure symbols in translation manager

src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationListHandler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.java, src/main/java/de/fraunhofer/aisec/cpg/graph/ConstructorDeclaration.java, src/main/java/de/fraunhofer/aisec/cpg/graph/MethodDeclaration.java, src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java, src/main/java/de/fraunhofer/aisec/cpg/graph/TranslationUnitDeclaration.java, src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java, src/main/java/de/fraunhofer/aisec/cpg/passes/ControlFlowGraphPass.java, src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java, src/main/java/de/fraunhofer/aisec/cpg/passes/FilenameMapper.java, src/main/java/de/fraunhofer/aisec/cpg/passes/ImportResolver.java, src/main/java/de/fraunhofer/aisec/cpg/passes/Pass.java, src/main/java/de/fraunhofer/aisec/cpg/passes/TypeHierarchyResolver.java, src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java, src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java, src/test/resources/include.cpp, src/test/resources/include.h
=> Improved parsing of method declarations

README.md, build.gradle.kts
=> Clean up and update of dependencies

src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java, src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java, src/main/java/de/fraunhofer/aisec/cpg/passes/Pass.java
EvaluationOrderGraphPass was assuming that frontend is not null, which it actually may be.
=> Fix a few NPEs

src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java, src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java
=> Add a way of completely disconnecting a node from the rest of the graph

src/main/java/de/fraunhofer/aisec/cpg/passes/ImportResolver.java, src/main/java/de/fraunhofer/aisec/cpg/passes/TypeHierarchyResolver.java, src/test/java/de/fraunhofer/aisec/cpg/TestUtils.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/StaticImportsTest.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/VariableResolverTest.java
=> Fix duplicate "unknown declarations" TU

src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java, src/main/java/de/fraunhofer/aisec/cpg/passes/BranchSemanticEOGPass.java, src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/BSEOGTest.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/JavaVsCppTest.java
Resolves #64 
Fixed StackOverflowError (thank you, @konradweiss !)
Fixed tests
=> Fix for #64

src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLiteralTest.java, src/test/resources/integer_literals.cpp
=> Properly stripping literal values of their prefix and suffix

src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java, src/main/java/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.java, src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java, src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/FunctionPointerTest.java, src/test/resources/functionPointers/func_ptr.c
=> Add support for reduced function pointer syntax

src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/graph/StaticCallExpression.java
=> Generate correct FQN for static calls

src/main/java/de/fraunhofer/aisec/cpg/graph/CallExpression.java, src/main/java/de/fraunhofer/aisec/cpg/graph/CompoundStatement.java, src/main/java/de/fraunhofer/aisec/cpg/graph/FunctionDeclaration.java, src/main/java/de/fraunhofer/aisec/cpg/graph/UnaryOperator.java, src/main/java/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.java, src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java, src/main/java/de/fraunhofer/aisec/cpg/sarif/PhysicalLocation.java
Signed-off-by: Julian Schuette <julian.schuette@aisec.fraunhofer.de>
=> Logging: Further reduce overly ambitious logging (resolve #92)

src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXBindingsTest.java, src/test/resources/bindings/replace_declaration.cpp, src/test/resources/bindings/use_then_declare.cpp
=> Fix Incorrect Bindings

src/main/java/de/fraunhofer/aisec/cpg/frontends/CallableInterface.java, src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/java/DemoTests.java
Closing #3 The class is restructured and the else-if construct is replaced by a handler structure similar to the Handler in the different Frontends. Although this does not decrease the size of the file, it makes it more readable and more searchable. Extracting more of the code into other classes was currently not done and can be done after identifying functional groups.
=> Refactor EOGPass to have a more readable and modular structure

.github/workflows/build.yml, build.gradle.kts, src/main/java/de/fraunhofer/aisec/cpg/graph/package-info.java
This PR publishes JavaDocs under https://fraunhofer-aisec.github.io/cpg/
Resolves https://github.com/Fraunhofer-AISEC/cpg/issues/119
=> Automatic CPG Documentation

src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java, src/test/resources/namespaces.cpp
=> Fixed potential copy/paste error in namespace declaration handling

src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java, src/test/java/de/fraunhofer/aisec/cpg/TestUtils.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java, src/test/resources/another-include.h, src/test/resources/include.cpp
Still a draft for now. Currently, only absolute paths are supported.
=> Support for black and whitelisting include files

src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java
=> add toplevel from configuration in include

src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java, src/test/java/de/fraunhofer/aisec/cpg/TypeTests.java
=> Fix parsing error when elaborated types are used as generics

src/main/java/de/fraunhofer/aisec/cpg/frontends/Handler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/graph/Expression.java, src/main/java/de/fraunhofer/aisec/cpg/graph/TranslationUnitDeclaration.java, src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java
=> Restored documented behaviour of loadIncludes

src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/graph/ConstructorDeclaration.java, src/main/java/de/fraunhofer/aisec/cpg/graph/MethodDeclaration.java, src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java
=> Fix for null annotations

src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontendFactory.java
=> Support hpp files

.github/workflows/build.yml, .github/workflows/check.yml
This PR adds a check in parallel to a regular build which tries to build the PR branch against codyze.
=> Codyze PR check

src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/graph/AnnotationMember.java, src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java, src/test/resources/Annotation.java
Basic implementation of Java annotations (not the declaration itself but the usage)
=> Java annotations

src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java, src/main/java/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.java
Seems to be the better way forward, also to satisfy SonarCloud's security hotspots.
=> using trySetAccessible instead of setAccessible

src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java, src/test/resources/Annotation.java
Looking also for single member annotations in Java now.
Closes #278
=> Fixed #278 by implementing single member annotations in Java

build.gradle.kts, src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java, src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java, src/test/java/de/fraunhofer/aisec/cpg/TestUtils.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/DFGTest.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/EOGTest.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/VisitorTest.java, src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java, src/test/resources/Issue285.java
This fixes #285 by properly parsing member call expressions.
=> Fixes for Java static calls

src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java, src/test/java/de/fraunhofer/aisec/cpg/enhancements/calls/CallResolverTest.java, src/test/resources/calls/calls.cpp
=> Fix Incorrect call resolution for functions outside of a class

build.gradle.kts, jitpack.yml
- added jitpack.yml to specify Java version
=> Added support for JitPack

src/main/python/main.py, src/test/java/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt, src/test/resources/python/ifexpr.py
* Added support for conditional expressions
* Do not add null statements to compound statement, resulting in neo4j errors
=> Added a small python fix

gradle.properties, src/main/python/main.py, src/test/java/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt, src/test/resources/python/class_ctor.py, src/test/resources/python/class_self.py, src/test/resources/python/simple_class.py
=> Python self and constructor support

build.gradle.kts, src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java
Closes #323 as the wrong type was set as referenced type
=> Closes #323

cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/UnaryOperator.java
=> Fixed NPEs in UnaryOperator

cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/Node.kt
Needed for Codyze, we need to set the ID to something unique in a pass.
=> Changed `Node::id` to `var`

cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
Close Jep interpreter also in case an exception occures.
=> Always close Jep interpreter #451

cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.java, cpg-library/src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java, cpg-library/src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java, cpg-library/src/test/resources/recordstmt.cpp
Added a failing test case for #491
=> CXX static field acecss

cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/typescript/TypeHandler.kt
Hotfix: Fixed NPE in TypeScript frontend
=> Fixed TypeScript NPE

cpg-console/build.gradle.kts, cpg-library/build.gradle.kts, cpg-neo4j/build.gradle.kts
=> Fixed kotlin runtime problems

.github/workflows/build.yml, build.gradle.kts, cpg-console/build.gradle.kts, cpg-library/src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java, gradle.properties, settings.gradle.kts
- Minor performance tweaks for the kotlin compiler
- Configured the possibility for Gradle scans (but turned them off by default)
=> Trying to improve the performance of gradle build

cpg-neo4j/src/main/java/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
=> Added `--enable-experimental-typescript` to enable TypeScript in `cpg-neo4j`

cpg-console/build.gradle.kts, cpg-library/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt
Better handling of a potential cast error
=> Fix cast error in template handling

cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.kt
Converted `getCurrentTypedefs` to a while-loop instead of a recursion.
Fixes #679
=> Fixing StackoverflowException in `ScopeManager::getCurrentTypedefs`

.github/workflows/build.yml, README.md, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/JepSingleton.kt, cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt, cpg-language-python/src/test/resources/python/issue473.py
=> Add test for issue #473

cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluator.kt, cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluatorTest.kt, cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/UnreachableEOGPassTest.kt, cpg-analysis/src/test/resources/value_evaluation/example.cpp
=> CPG-Analysis: Fix evaluation of values with different types

cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationResult.java, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/Graph.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/helpers/MeasurementBenchmark.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/helpers/MeasurementHolder.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/StatisticsCollectionPass.kt, cpg-core/src/test/java/de/fraunhofer/aisec/cpg/PerformanceRegressionTest.kt, cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguageFrontend.kt, cpg-neo4j/src/main/java/de/fraunhofer/aisec/cpg_vis_neo4j/Application.kt
Introduce some methods to add intermediate steps and rename classes
=> Ensure backwards compatibility to cpg version < 4.4.0

cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/HasType.java
Fixes javadoc error in JitPack build
=> Fixing javadoc error in JitPack build

.github/workflows/build.yml, build.gradle.kts
=> Using dokka instead of javadoc

cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/RecordDeclaration.java, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/ProblemExpression.kt, cpg-language-go/src/main/golang/declarations.go, cpg-language-go/src/main/golang/expressions.go, cpg-language-go/src/main/golang/frontend/handler.go, cpg-language-go/src/main/golang/types.go, cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/DeclarationTest.kt, cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/ExpressionTest.kt, cpg-language-go/src/test/resources/golang/embed.go, cpg-language-go/src/test/resources/golang/type_assert.go, cpg-language-go/src/test/resources/golang/unnamed.go
Mainly crash fixes and some implementation improvements
* Fixes #890
* Fixes #891
* Fixes #892
* Fixes #894 
* Fixes #895
=> Various improvements to the Go language frontend

cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt, cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLiteralTest.kt, cpg-core/src/test/resources/integer_literals.cpp
=> Support C++14 integer literal with single quotes

cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/LoopScope.kt
This PR adds a custom getter for `conditions` in `LoopScope` to get the condition of the corresponding loop statement.
=> Add getter for `conditions` in `LoopScope`

cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.kt
=> Add location to reference of member call

cpg-core/specifications/dfg.md, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/DFGPass.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt
Moving DFG edges that show relation between data and branching nodes from the EOG pass that models branching to the DFG pass as the responsible for DFG edges.
This does not change the graphs structure and only refactors DFG edge creation to reduce the fragmentation of that code semantic.
=> Moving remaining DFG edge creation from EOG pass to DFG pass.

cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/Extensions.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/BooleanType.kt, cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt, cpg-core/src/testFixtures/kotlin/de/fraunhofer/aisec/cpg/frontends/TestLanguage.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguage.kt, cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguage.kt, cpg-language-llvm/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/llvm/LLVMIRLanguage.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt, cpg-language-typescript/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/typescript/JavaScriptLanguage.kt, cpg-language-typescript/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/typescript/TypeScriptLanguage.kt
This PR is a cleanup and improvement for the built-in types for all supported languages
=> Improvement of built-in types for all supported languages

build.gradle.kts, jitpack.yml, settings.gradle.kts
=> Fixed JitPack build

.github/workflows/build.yml, build.gradle.kts, cpg-all/build.gradle.kts
This PR makes use of the new gradle feature of aggregated jacoco reports (see https://docs.gradle.org/current/userguide/jacoco_report_aggregation_plugin.html)
=> Trying to merge code coverage

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/PopulatedByPass.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/ValueDeclaration.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/DeclaredReferenceExpression.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/types/Type.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeHierarchyResolver.kt
Annotates properties which are set by passes
Fixes #233 .
=> Annotate properties with PopulatedByPass

README.md
=> Reference eog spec in readme

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationResult.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt
=> Made `additionalNodes` a mutable set on public interface

docs/docs/index.md
There was an error in numbering boxes which let mkdocs render the page weirdly
=> Fix documentation page

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CallResolver.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EdgeCachePass.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/FilenameMapper.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeHierarchyResolver.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/TypeResolver.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.kt
This maintains the extendabillity of our passes system. Apparently we did not pay attention to keep protected as default.
=> Changing visibility to protected for all members of passes

cpg-language-typescript/build.gradle.kts, gradle/libs.versions.toml, jitpack.yml
This PR upgrades transitive dependencies because of known security issues.
=> Upgraded transitive dependencies

CONTRIBUTING.md, README.md, docs/docs/Contributing/index.md
Updates the readme and contributing markdowns.
Fixes #1271
=> Readme updates

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Handler.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/Util.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
This PR fixes smaller things such as proper display of the log source by inlining the log functions. It also fixes other smaller issues.
=> Smaller fixes in logging and utils

cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
This PR improves the `codeOf` functionality for Python.
=> Python improve codeOf

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/Pass.kt
The list of EOG starter nodes were duplicate
=> Fixed issue with EOG starter passes

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/MermaidPrinter.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edge/Dataflow.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edge/Properties.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edge/PropertyEdge.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/Reference.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DFGPass.kt, cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/MermaidPrinterTest.kt
This PR adds specific classes for our property edges. Starting with `Dataflow`. We will extend this in the future.
=> Adding specific classes for property edges, such as `Dataflow`

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DynamicInvokeResolver.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoHandler.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguage.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontend.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoStandardLibrary.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoUtils.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/SpecificationHandler.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt, cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt, cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/IntegrationTest.kt, cpg-language-go/src/test/resources/golang/complex_resolution/calls/calls.go, cpg-language-go/src/test/resources/golang/literal.go, cpg-language-go/src/test/resources/golang/packages/api/apiv1.go, cpg-language-go/src/test/resources/golang/packages/cmd/packages/packages.go, cpg-language-go/src/test/resources/golang/packages/packages.go, cpg-language-go/src/test/resources/golang/types.go
This includes better handling of (underlying) types as well as better handling of packages.
=> More improvements to the Go frontend

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt, cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
=> Fix index out of bounds in `hasSignature`

cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/ExpressionHandler.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
=> Python: Add BoolOp and + or

cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/JavaExternalTypeHierarchyResolver.kt
A type is resolved to then resolve its super types, in some cases this fails when an inferred type unknown to the java parser appears to fail. We catch the error similar to the case where resolution of the supertypes fail and do not further try to resolve the type.
While in a prior Issue with the Javaparser we decided to use our internal resolution through the scope manager, I don't think we are currently able to parse type hierarchies from the entirety of the code.
=> Ignore Type resolution error when resolving super types through `javaparser`

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TypeManager.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/CXXCallResolverHelper.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt, cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CLanguage.kt, cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguage.kt
This should have been part of https://github.com/Fraunhofer-AISEC/cpg/pull/1496 but I forgot to clean this up.
=> Some cleanup after next-generation call resolving

cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt, cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.kt
Hopefully fixes #1546
Feel free to comment whether the solution helps to do so.
=> Model values of Enum entries in Java with constructor call

.github/workflows/build.yml, buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
Hopefully this works. Thanks to @milux for support.
=> Trying to parallelize everything except performance tests

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DynamicInvokeResolver.kt
In some cases, the pointer type can be a `ProblemType`, which caused a casting error:
```
Caused by: java.lang.ClassCastException: class de.fraunhofer.aisec.cpg.graph.types.ProblemType cannot be cast to class de.fraunhofer.aisec.cpg.graph.types.FunctionPointerType (de.fraunhofer.aisec.cpg.graph.types.ProblemType and de.fraunhofer.aisec.cpg.graph.types.FunctionPointerType are in unnamed module of loader 'app')
at de.fraunhofer.aisec.cpg.passes.DynamicInvokeResolver.handleCallee(DynamicInvokeResolver.kt:115)
at de.fraunhofer.aisec.cpg.passes.DynamicInvokeResolver.handleCallExpression(DynamicInvokeResolver.kt:94)
at de.fraunhofer.aisec.cpg.passes.DynamicInvokeResolver.handle(DynamicInvokeResolver.kt:79)
at de.fraunhofer.aisec.cpg.passes.DynamicInvokeResolver.accept$lambda$0(DynamicInvokeResol …
```
=> Catch ProblemType inside DynamicInvokeResolver.handleCallee

cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclaratorHandler.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
This PR implements the new operator overloading functionality for the Python language.
=> Python operators

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/DeclarationBuilder.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/HasBase.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/HasOperatorCode.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/OperatorDeclaration.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/BinaryOperator.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/MemberCallExpression.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/MemberExpression.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/UnaryOperator.kt, cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CPPLanguage.kt, cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/DeclaratorHandler.kt, cpg-language-cxx/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/CXXDeclarationTest.kt, cpg-language-cxx/src/test/resources/cxx/operators/arithmetic.cpp, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt
This PR adds support for an operator declaration. They are not resolved yet. Resolution of overloaded operators will be tackled in #1606
=> Added `OperatorDeclaration`

cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/JepSingleton.kt
We also take the first path and then break, so that it won't get overidden.
=> Displaying info about which JEP path is used

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/StatementBuilder.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt, cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/ScopeTest.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/PythonAddDeclarationsPass.kt, cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt, cpg-language-python/src/test/resources/python/packages/foobar/__main__.py, cpg-language-python/src/test/resources/python/packages/foobar/config/__init__.py, cpg-language-python/src/test/resources/python/packages/foobar/implementation/__init__.py, cpg-language-python/src/test/resources/python/packages/foobar/implementation/internal_bar.py, cpg-language-python/src/test/resources/python/packages/foobar/implementation/internal_foo.py
This PR adds (basic) support for python *packages* in addition to python *modules*.
=> Support for python packages

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/NodeBuilder.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt
Handles async with just like the normal with
=> Support async with in python

cpg-language-cxx/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cxx/ExpressionHandler.kt
There shouldn't be an assert in a frontend.
=> CXX frontend: remove assert

README.md
=> add the INI frontend to README.md

cpg-language-ini/src/main/kotlin/de/fraunhofer/aisec/cpg/frontend/configfiles/IniFileFrontend.kt
IMporting more CPG classes makes the doc string more readable.
=> improve kdoc by importing more stuff

cpg-language-go/build.gradle.kts
Updated deps to new release (v0.0.5) and added dll file for windows support
=> Updated deps to version v0.0.5 and added windows lib file (dll)

cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/Query.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpRequest.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt
It may be useful to extend the concepts as follows:
* Add property in HttpRequest to link it to an HttpEndpoint
=> Extend concepts

cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/EvaluateExtensions.kt, cpg-concepts/build.gradle.kts, cpg-concepts/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/concepts/MemoryTest.kt, cpg-concepts/src/integrationTest/resources/python/encrypt_with_key.py, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/CipherOperation.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/memory/Memory.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt, cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/statementHandler/StatementHandlerTest.kt
Including an integration / test example how to use it by using a key for encryptio and then properly deallocating it in all branches
=> Added basic concepts for memory operations

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Component.kt
Otherwise, we will crash with an exception
=> Added `@DoNotPersist` to `Component::topLevel`

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/collections/UnwrappedEdgeCollection.kt, cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/edges/EdgesTest.kt
=> Added a `toString` to UnwrappedEdgeCollection

cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguageFrontend.kt
#2026 -> disable parallel support for Python as suggested by @oxisto
=> Python: disable parallel support

cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extension.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/Concept.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/Operation.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/BlockStorage.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/Cipher.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/DiskEncryption.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/Secret.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpClient.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpEndpoint.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpRequestHandler.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/memory/DynamicLoading.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/memory/Memory.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/memory/CXXDynamicLoadingPass.kt, cpg-neo4j/src/integrationTest/kotlin/de/fraunhofer/aisec/neo4j/Neo4JTest.kt
Currently, the `Concept` node requires the type of `Operation` connected to it, which makes some things difficult. This PR releases this tight connection.
=> Untangle Concept and Operation

cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt, cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonFrontendTest.kt
This is my attempt of interpreting the rules of python imports. I am not sure if this really reflects https://docs.python.org/3/reference/simple_stmts.html#the-import-statement but it reflects what happens when I execute CPython.
Fixes #2060
=> Importing nested import paths

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/Edge.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/edges/flows/ProgramDependence.kt
=> Move dependence field to ProgramDependence class

docs/docs/CPG/specs/dfg.md, docs/docs/GettingStarted/query.md, docs/docs/GettingStarted/shortcuts.md, docs/docs/index.md
Updates the documentation page to account for the changes in the Query and Extension API following EOG and DFGs.
Fixes #2067
=> Updates the documentation for new extensions

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
Should be a smoother experience now. Previously, we had a lot of (incorrect) warnings that were produced because of cross-component import dependencies of translation units. But because we already process components in the correct order and THEN process the individual TUs inside id, we can remove import dependencies to other components.
=> Produce less warnings when resolving imports

SECURITY.md, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/auth/Authentication.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpClient.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpEndpoint.kt
Add Concepts and Operations for Authentication
=> Concept and Operations for Authentication

.github/workflows/build.yml, build.gradle.kts, buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts
=> Using Codecov to display test results

cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/auth/Authentication.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/config/Configuration.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/Cipher.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/CipherOperation.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/diskEncryption/DiskEncryption.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/file/File.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/file/FileBuilder.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/flows/EntryPoint.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpClient.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpEndpoint.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpRequest.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/logging/LogWrite.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/memory/DynamicLoading.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/memory/Memory.kt
The missing equals/hashcode was a major BUG that lead to weird issues.
=> Implement equals/hashcode on all concepts and operations

cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpEndpoint.kt
Changed `authentication` prop to `var` for setting the authentication in `AuthenticationPass`
=> Change `authentication` property in `HttpEndpoint` to var

cpg-concepts/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/concepts/MemoryTest.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/file/python/PythonFileConceptPass.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.kt, cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/graph/declarations/TupleDeclarationTest.kt, cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/DFGTest.kt
Since we have EOGStarters now, we can disable this early return.
---------
Co-authored-by: KuechA <31155350+KuechA@users.noreply.github.com>
=> CFSDFG: also for non-FunctionDeclarations

.run/Codyze Compliance Scan (with Console and Example).run.xml, codyze-console/src/main/kotlin/de/fraunhofer/aisec/codyze/console/Nodes.kt, codyze-console/src/test/kotlin/ApplicationTest.kt, codyze-console/src/test/kotlin/de/fraunhofer/aisec/codyze/console/ApplicationTest.kt, codyze-console/src/test/kotlin/de/fraunhofer/aisec/codyze/console/NodesTest.kt
=> Fixed bug with absolute path missing

cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/auth/Authorization.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpConceptBuilder.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/http/HttpEndpoint.kt
Adds an abstract Authorization concept
=> `Authorization` Concept

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/assumptions/Assumption.kt
If further types are needed or the difference between types is not clear enough, we can make further changes in this PR or create a new one. I expect us to identify shortcomings of the existing types while adding assumptions to our implementation.
=> Add asssumption types doc and change some typenames

codyze-core/build.gradle.kts, codyze-core/src/integrationTest/kotlin/de/fraunhofer/aisec/codyze/CodyzeExecutorTest.kt, codyze-core/src/integrationTest/kotlin/de/fraunhofer/aisec/codyze/ConceptScriptPassTest.kt, codyze-core/src/integrationTest/kotlin/de/fraunhofer/aisec/codyze/QueryHostTest.kt, codyze-core/src/integrationTest/kotlin/de/fraunhofer/aisec/codyze/SarifTest.kt, codyze-core/src/integrationTest/resources/example/example.codyze.kts, codyze-core/src/integrationTest/resources/example/src/module1/main.py, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/CodyzeExecutor.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/CodyzeScriptCompilationConfiguration.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/ConceptScriptDefinition.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/dsl/Annotations.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/dsl/Dsl.kt, codyze-core/src/test/kotlin/de/fraunhofer/aisec/codyze/dsl/DslTest.kt, cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryTree.kt, gradle/libs.versions.toml
Non-functional at the moment, this is just the API definition, which is also subject to change.
=> Initial API for Codyze DSL

codyze-core/build.gradle.kts, codyze-core/src/integrationTest/kotlin/de/fraunhofer/aisec/codyze/CodyzeExecutorTest.kt, codyze-core/src/integrationTest/resources/example/manual-assessments.codyze.kts, codyze-core/src/integrationTest/resources/example/project.codyze.kts, codyze-core/src/integrationTest/resources/example/src/module1/main.py, codyze-core/src/integrationTest/resources/example/src/third-party/mylib/library/lib.py, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/CodyzeExecutor.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/CodyzeScriptCompilationConfiguration.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/Project.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/dsl/Dsl.kt, codyze-core/src/test/kotlin/de/fraunhofer/aisec/codyze/dsl/DslTest.kt
This PR tries to connect the Codyze DSL to the already existing infrastructure for an `AnalysisProject`.
=> Make Codyze DSL functional

cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/FlowQueries.kt, cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/DataflowQueriesTest.kt, cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/testcases/FlowQueriesTest.kt
=> Test and update the function `dataFlowWithValidator`

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/assumptions/Assumption.kt
Also we will now hard-crash if we violate the assumption's assumption about having either a node or edge
=> Fixed assumption debug spam

cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/EOGConceptPass.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/Extensions.kt, cpg-concepts/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/TagOverlaysPassTest.kt
Initial suggestion to implement nested tagging logic.
=> Allow nested tagging logic

cpg-concepts/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/OverlayNodeEquality.kt, cpg-concepts/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/TagOverlaysPassTest.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/OverlayNode.kt
=> New implementation of OverlayNode.equals

buildSrc/src/main/kotlin/cpg.common-conventions.gradle.kts, codyze-core/src/integrationTest/kotlin/de/fraunhofer/aisec/codyze/CodyzeScriptHostTest.kt, codyze-core/src/integrationTest/resources/example/manual.codyze.kts, codyze-core/src/integrationTest/resources/example/project.codyze.kts, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/CodyzeScript.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/Project.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/dsl/Dsl.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/dsl/QueryTreeExtensions.kt, codyze-core/src/test/kotlin/de/fraunhofer/aisec/codyze/dsl/DslTest.kt, cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryStates.kt
This PR integrates the 4-state decision (state) of #2319 into the Codyze DSL.
=> Integration of Decision into Codyze DSL

codyze-core/src/integrationTest/kotlin/de/fraunhofer/aisec/codyze/CodyzeScriptHostTest.kt, codyze-core/src/integrationTest/resources/example/tagging.codyze.kts, cpg-concepts/src/integrationTest/kotlin/de/fraunhofer/aisec/cpg/concepts/MemoryTest.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/crypto/encryption/Builder.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/crypto/encryption/CipherOperation.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/crypto/encryption/CreateSecret.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/crypto/encryption/Encryption.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/crypto/encryption/GetSecret.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/crypto/encryption/Secret.kt, cpg-concepts/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/concepts/crypto/encryption/SecretOperation.kt, cpg-concepts/src/test/kotlin/de/fraunhofer/aisec/cpg/passes/concepts/TagOverlaysPassTest.kt
- Moved `Secret` to generic crypto package
- Added from `Secrfrom `Secret` to `GetSecret
=> Cleanup of `Secret`

cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/DataflowQueriesTest.kt, cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/query/ExecutionOrderQueriesTest.kt, cpg-analysis/src/test/kotlin/de/fraunhofer/aisec/cpg/testcases/FlowQueriesTest.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/AnalysisConfiguration.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Extensions.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Node.kt
=> Improved loop detection

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/InferenceConfiguration.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/PassHelper.kt
This PR moves field inference to the proper place, the `Inference` class.
Fixes #2352
=> Better field inference

codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/Project.kt, codyze-core/src/main/kotlin/de/fraunhofer/aisec/codyze/dsl/Dsl.kt, cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/query/QueryStates.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationResult.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/assumptions/Assumption.kt, cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/assumptions/AssumptionTest.kt
=> Setting assumption status in `Assumption` creation

cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Name.kt, cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/sarif/PhysicalLocation.kt, cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/StatementHandler.kt, cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/statementHandler/WithStatementTest.kt
Instead derive something from node hash codes
Fixes https://github.com/Fraunhofer-AISEC/cpg/issues/2364
=> Do not use a random name for temporary names
